// Runtime module 4/9: deterministic portfolio map data.
const principlesSourceHref = "https://app.notion.com/p/digital-web-digital-f68fc13247614ccb9738d9a85acf29b4?source=copy_link#70405c2623e342fb98d027c8634f2207";

// reel-chapter-manifest:start
const reelChapterSources = new Map([
  ["garage-site", [
      "assets/reel-chapters/garage-site-01.mp4?v=d231d9f246e7",
      "assets/reel-chapters/garage-site-02.mp4?v=a185b6d535dc",
  ]],
  ["narkomfin", [
      "assets/reel-chapters/narkomfin-01.mp4?v=8a8b8eba97b7",
      "assets/reel-chapters/narkomfin-02.mp4?v=b0a3640e9a1e",
  ]],
  ["collection", [
      "assets/reel-chapters/garage-collection-01.mp4?v=c458378b08fa",
      "assets/reel-chapters/garage-collection-02.mp4?v=13b73239ecf4",
  ]],
  ["garage-archives", [
      "assets/reel-chapters/garage-archives-01.mp4?v=78c2b0318e41",
      "assets/reel-chapters/garage-archives-02.mp4?v=d86e9d4cf111",
  ]],
  ["garage-courses", [
      "assets/reel-chapters/garage-courses-01.mp4?v=685692edbaeb",
      "assets/reel-chapters/garage-courses-02.mp4?v=295cc2a59b38",
  ]],
  ["garage-webzine", [
      "assets/reel-chapters/garage-webzine-01.mp4?v=78b46830a8ed",
      "assets/reel-chapters/garage-webzine-02.mp4?v=93e6e21719a3",
  ]],
  ["garage-institutions", [
      "assets/reel-chapters/garage-institutions-01.mp4?v=e9516d43f06b",
      "assets/reel-chapters/garage-institutions-02.mp4?v=b138a9b90b19",
  ]],
  ["garage-endowment", [
      "assets/reel-chapters/garage-endowment-01.mp4?v=bd5d5e55e721",
      "assets/reel-chapters/garage-endowment-02.mp4?v=25a4d5b65e08",
  ]],
  ["shirokostup", [
      "assets/reel-chapters/shirokostup-01.mp4?v=9a2ca8be0932",
      "assets/reel-chapters/shirokostup-02.mp4?v=f3312ac0f305",
  ]],
  ["tarski", [
      "assets/reel-chapters/tarski-01.mp4?v=9991bad25583",
      "assets/reel-chapters/tarski-02.mp4?v=ba7327082282",
  ]],
  ["herman", [
      "assets/reel-chapters/herman-01.mp4?v=af3ea87a0934",
      "assets/reel-chapters/herman-02.mp4?v=7196d29d1d8f",
  ]],
  ["hotline-camp", [
      "assets/reel-chapters/hotline-camp-01.mp4?v=de23ead77824",
      "assets/reel-chapters/hotline-camp-02.mp4?v=4f83a0d2671b",
  ]],
  ["dusty", [
      "assets/reel-chapters/dusty-merch-01.mp4?v=7219d4df4177",
      "assets/reel-chapters/dusty-merch-02.mp4?v=fb7fc0b2ed31",
  ]],
  ["dd-camp", [
      "assets/reel-chapters/dusty-camp-01.mp4?v=8a8b672a45a0",
      "assets/reel-chapters/dusty-camp-02.mp4?v=0fec39e9dd30",
  ]],
  ["eleven", [
      "assets/reel-chapters/11111-01.mp4?v=33263c3024e2",
      "assets/reel-chapters/11111-02.mp4?v=2129a4eaa56a",
  ]],
  ["ks-fish", [
      "assets/reel-chapters/ks-fish-01.mp4?v=556fd200a8ab",
      "assets/reel-chapters/ks-fish-02.mp4?v=b208d435b423",
  ]],
  ["doronin", [
      "assets/reel-chapters/doronin-01.mp4?v=dbdbce0d7ac3",
      "assets/reel-chapters/doronin-02.mp4?v=cd75b564305b",
  ]],
]);
// reel-chapter-manifest:end

const mapItems = [
  {
    id: "garage",
    kind: "company",
    label: "МУЗЕЙ «ГАРАЖ»",
    title: "МУЗЕЙ «ГАРАЖ»",
    meta: "ОКТ 2021—МАР 2025 / СТАРШИЙ МЕНЕДЖЕР ВЕБ-РАЗРАБОТКИ",
    description: "Самый важный профессиональный период: здесь сошлись культура, продукт, исследования, дизайн и масштабная веб-разработка.",
    timeYear: 2023,
    timeLabel: "2021—2025",
    href: "https://garagemca.org/ru",
    kindLabel: "ИНСТИТУЦИЯ / 2021—2025",
    x: 46,
    y: 14,
    size: 76,
  },
  {
    id: "private-practice",
    kind: "project",
    accentKind: "practice",
    label: "ЧАСТНАЯ ПРАКТИКА",
    title: "ЧАСТНАЯ ПРАКТИКА",
    meta: "СЕЙЧАС / НЕБОЛЬШИЕ ЦИФРОВЫЕ ПРОЕКТЫ",
    description: "Самостоятельная работа с небольшими проектами: разобраться в задаче, найти собственную форму и довести продукт до запуска.",
    timeYear: 2023,
    timeLabel: "2020—СЕЙЧАС",
    kindLabel: "ПРАКТИКА / СВЯЗУЮЩИЙ УЗЕЛ",
    x: 61,
    y: 43,
    size: 38,
  },
  {
    id: "optimal",
    kind: "company",
    label: "ОПТИМАЛГРУПП",
    title: "ЦИФРОВОЕ АГЕНТСТВО «ОПТИМАЛГРУПП»",
    meta: "МАР 2025—АПР 2026 / МЕНЕДЖЕР ПРОЕКТОВ",
    description: "В агентстве вёл клиентские сайты и сервисы; главный кейс — год управления развитием Строительной академии ТЕХНОНИКОЛЬ.",
    timeYear: 2025.5,
    timeLabel: "2025—2026",
    href: "https://optimalgroup.ru/projects/academy-tn-ru/",
    linkLabel: "ОТКРЫТЬ КЕЙС",
    kindLabel: "КОМПАНИЯ / АГЕНТСТВО",
    x: 24,
    y: 18,
    size: 29,
  },
  {
    id: "early-career",
    kind: "company",
    label: "РАННИЕ РОЛИ",
    title: "ОТ КОНТЕНТА К ПРОДУКТУ",
    meta: "ОКТ 2010—АПР 2016 / КОНТЕНТ → ЭЛЕКТРОННАЯ ТОРГОВЛЯ → ПРОДУКТ",
    description: "Начал с контента и электронной торговли в «ВАЛЛЕКС М», затем развивал сайты и интернет-продвижение «ИльмиксГрупп», а в Freya Project уже отвечал за весь продукт — от идеи и UX до продаж, маркетинга и сообщества.",
    timeYear: 2013,
    timeLabel: "2010—2016",
    href: "https://hh.ru/resume/e469b9deff00850af10039ed1f736563726574?print=true",
    linkLabel: "ПОЛНОЕ РЕЗЮМЕ НА HH.RU",
    kindLabel: "ОПЫТ / 2010—2016",
    x: 8,
    y: 22,
    size: 22,
  },
  {
    id: "ilmix",
    kind: "company",
    label: "ИЛЬМИКСГРУПП",
    title: "«ИЛЬМИКСГРУПП»",
    meta: "5 ЛЕТ / ЦИФРОВОЕ НАПРАВЛЕНИЕ",
    description: "Запускал и развивал digital-продукты в сфере MedTech и health media — от нишевых медиа до внутренних корпоративных платформ и MVP-сервисов для врачей. Отвечал за продуктовую стратегию, UX, рост аудитории, запуск новых каналов и эксперименты с форматами.",
    timeYear: 2018.5,
    timeLabel: "2017—2020",
    kindLabel: "КОМПАНИЯ / ВНУТРЕННЯЯ КОМАНДА",
    x: 16,
    y: 30,
    size: 38,
  },
  {
    id: "garage-site",
    parent: "garage",
    kind: "project",
    label: "САЙТ МУЗЕЯ",
    title: "САЙТ МУЗЕЯ «ГАРАЖ»",
    meta: "UX / UI / ДИЗАЙН-ИНЖИНИРИНГ / ВЕБ-МЕНЕДЖМЕНТ",
    description: "Главный цифровой продукт Музея: постоянный цикл исследований, приоритизации и релизов новых функций и сервисов.",
    timeYear: 2023,
    timeLabel: "2021—2025",
    href: "https://garagemca.org/",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-site.mp4?v=4ebed322d029",
    previewOrientation: "landscape",
    previewMeta: "ГЛАВНАЯ, КАЛЕНДАРЬ И МЕДИА / 00:08",
    x: 58,
    y: 14,
    size: 23,
  },
  {
    id: "narkomfin",
    parent: "garage",
    kind: "project",
    label: "ДОМ НАРКОМФИНА",
    title: "ДОМ НАРКОМФИНА",
    meta: "ДИЗАЙН / UX / UI / ЦИФРОВОЙ ОПЫТ",
    description: "Дизайн сайта Дома Наркомфина — от интерактивной модели здания и световых состояний до календаря и цельной цифровой навигации.",
    timeYear: 2023,
    href: "https://narkomfin.ru/",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/narkomfin.mp4?v=b03bf2a31888",
    previewPoster: "assets/reel-posters/narkomfin.jpg?v=a612d43dea12",
    previewOrientation: "landscape",
    previewMeta: "МОДЕЛЬ, РАЗДЕЛЫ И ТЕМЫ / 00:13",
    x: 67,
    y: 21,
    size: 25,
  },
  {
    id: "collection",
    parent: "garage",
    kind: "project",
    label: "КОЛЛЕКЦИЯ",
    title: "КОЛЛЕКЦИЯ И ОТКРЫТОЕ ХРАНЕНИЕ",
    meta: "2024 / ПРОДУКТ / ИССЛЕДОВАНИЕ / ЗАПУСК",
    description: "Запуск каталога коллекции и открытого хранения: продуктовая логика, исследования, интерфейс и координация реализации.",
    timeYear: 2024,
    href: "https://garagemca.org/collection/catalogue",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-collection.mp4?v=83401a311a20",
    previewOrientation: "landscape",
    previewMeta: "КАТАЛОГ И ОТКРЫТОЕ ХРАНЕНИЕ / 00:08",
    x: 75,
    y: 19,
    size: 22,
  },
  {
    id: "garage-archives",
    parent: "garage",
    kind: "project",
    label: "АРХИВЫ",
    title: "АРХИВНЫЕ ПРОЕКТЫ",
    meta: "АРХИВ РОССИЙСКОГО ИСКУССТВА / I-M-I / NNS",
    description: "Поддержка и развитие цифровых архивов — от повседневных задач до проектирования новых сценариев доступа к материалам.",
    href: "https://russianartarchive.net/ru",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-archives.mp4?v=9b3370ed7e66",
    previewPoster: "assets/reel-posters/garage-archives.jpg?v=81aadd292d4e",
    previewOrientation: "landscape",
    previewMeta: "КАТАЛОГ, ПОИСК И АРХИВНЫЕ МАТЕРИАЛЫ / 00:12",
    x: 59,
    y: 28,
    size: 18,
  },
  {
    id: "garage-courses",
    parent: "garage",
    kind: "project",
    label: "ОНЛАЙН-КУРСЫ",
    title: "ОНЛАЙН-КУРСЫ МУЗЕЯ",
    meta: "ОБУЧЕНИЕ / ПРОДУКТ / ПАРТНЁРСТВА",
    description: "Бесплатные образовательные продукты: запуск курсов, улучшение сценариев и работа с партнёрами.",
    href: "https://garagemca.org/learn/online-courses",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-courses.mp4?v=15acbed30144",
    previewOrientation: "landscape",
    previewMeta: "КУРСЫ И УЧЕБНЫЕ СЦЕНАРИИ / 00:07",
    x: 80,
    y: 30,
    size: 17,
  },
  {
    id: "garage-app",
    parent: "garage",
    kind: "project",
    label: "Я ИДУ В МУЗЕЙ",
    title: "«Я ИДУ В МУЗЕЙ»",
    meta: "ДОСТУПНОСТЬ / МОБИЛЬНЫЙ ПРОДУКТ / ПЕРЕЗАПУСК",
    description: "Перезапуск приложения для людей с ментальными особенностями и их близких: доступность, навигация и понятный маршрут.",
    timeYear: 2024,
    href: "https://apps.apple.com/ru/app/я-иду-в-музей/id1558275984",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    x: 84,
    y: 46,
    size: 17,
  },
  {
    id: "garage-webzine",
    parent: "garage",
    kind: "project",
    label: "ВЕБ-ЗИН",
    title: "«НЕЧЕЛОВЕЧЕСКИЕ ЖИВОТНЫЕ И ТЕХНИКА»",
    meta: "ИССЛЕДОВАНИЕ / ДИЗАЙН-ИНЖИНИРИНГ / КОД",
    description: "Интернет-журнал по текстам ридинг-группы, собранный вручную как самостоятельная цифровая форма.",
    href: "https://non-human-animals.garage.digital/index.html",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-webzine.mp4?v=ffe8ffd234f8",
    previewPoster: "assets/reel-posters/garage-webzine.jpg?v=461addd9b6aa",
    previewOrientation: "landscape",
    previewMeta: "ГЛАВНАЯ, ТЕКСТ И ТЁМНАЯ ТЕМА / 00:12",
    x: 72,
    y: 34,
    size: 15,
  },
  {
    id: "garage-institutions",
    parent: "garage",
    kind: "project",
    label: "ПОМОЩЬ ИНСТИТУЦИЯМ",
    title: "ПОМОЩЬ КУЛЬТУРНЫМ ИНСТИТУЦИЯМ",
    meta: "КОНСУЛЬТАЦИИ / ДИЗАЙН / ТЕХНИЧЕСКАЯ ПОМОЩЬ",
    description: "Знания, консультации и конкретная техническая помощь культурным институциям и НКО — с акцентом на быстрый запуск.",
    href: "https://radiancecca.com/",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-institutions.mp4?v=44317e2d8066",
    previewPoster: "assets/reel-posters/garage-institutions.jpg?v=186a13863205",
    previewOrientation: "landscape",
    previewMeta: "СОБЫТИЯ, НАПРАВЛЕНИЯ И ПОСЕЩЕНИЕ / 00:12",
    x: 55,
    y: 37,
    size: 16,
  },
  {
    id: "garage-endowment",
    parent: "garage",
    kind: "project",
    label: "ЭНДАУМЕНТ",
    title: "ЭНДАУМЕНТ-ФОНД МУЗЕЯ",
    meta: "ПОДДЕРЖКА / РАЗВИТИЕ / КОНТЕНТ",
    description: "Поддержка и развитие отдельного цифрового продукта эндаумент-фонда Музея.",
    href: "https://endowment.garagemca.org/ru/",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-endowment.mp4?v=bb8a0d8f6fcd",
    previewPoster: "assets/reel-posters/garage-endowment.jpg?v=60c74c68c8c0",
    previewOrientation: "landscape",
    previewMeta: "МИССИЯ, ЦЕЛЕВЫЕ КАПИТАЛЫ И ПОЖЕРТВОВАНИЕ / 00:11",
    x: 53,
    y: 26,
    size: 12,
  },
  {
    id: "shirokostup",
    parent: "private-practice",
    kind: "project",
    label: "SHIROKOSTUP",
    mapLabel: "Сайт независимого куратора и исследователя Ольги Широкоступ",
    title: "САЙТ ОЛЬГИ ШИРОКОСТУП",
    meta: "РЕДАКЦИОННЫЙ ДИЗАЙН / САЙТ / 2026",
    description: "Портфолио куратора и исследовательницы: редакционная структура, спокойный интерфейс и возможность самостоятельно вести сайт.",
    timeYear: 2026,
    href: "https://shirokostup.site/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/shirokostup.mp4?v=d7ddd88fb536",
    previewPoster: "assets/reel-posters/shirokostup.jpg?v=74222ef366e9",
    previewOrientation: "landscape",
    previewMeta: "ГЛАВНАЯ, МЕНЮ И ТЁМНАЯ ТЕМА / 00:13",
    x: 82,
    y: 52,
    size: 22,
  },
  {
    id: "tarski",
    parent: "private-practice",
    kind: "project",
    label: "TARSKI",
    mapLabel: "Сайт Tarski — среды для изучения и поддержки социально ориентированного и вовлекающего искусства",
    title: "TARSKI",
    meta: "ЦИФРОВОЙ ПРОДУКТ / САЙТ",
    description: "Цифровая среда для программы, сообщества и материалов Tarski: ясная логика, цельный интерфейс и основа для дальнейшего развития.",
    timeYear: 2026,
    href: "https://tarski.ru/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/tarski.mp4?v=8c70e36007eb",
    previewOrientation: "landscape",
    previewMeta: "СООБЩЕСТВО И ПРОГРАММА / 00:12",
    x: 78,
    y: 47,
    size: 23,
  },
  {
    id: "herman",
    parent: "private-practice",
    kind: "project",
    label: "HERMAN & CO",
    mapLabel: "Сайт стилиста и эксперта по уходу Германа Винокурова",
    title: "HERMAN & CO",
    meta: "ПРОФИЛЬ / САЙТ",
    description: "Интерактивный профиль стилиста и барбера: опыт, экспертиза, медиа, партнёрства и прямой вход в запись.",
    timeYear: 2026,
    href: "https://barberherman.ru/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/herman.mp4?v=4f63a85a9558",
    previewPoster: "assets/reel-posters/herman.jpg?v=46c67a36856b",
    previewOrientation: "landscape",
    previewMeta: "ПРОФИЛЬ, МЕДИА И ПЛЕЙЛИСТЫ / 00:15",
    x: 82,
    y: 58,
    size: 19,
  },
  {
    id: "hotline-camp",
    parent: "private-practice",
    kind: "project",
    label: "HOTLINE CAMP",
    mapLabel: "Сайт предстартового кэмпа по триатлону Hotline Camp",
    title: "HOTLINE CAMP",
    meta: "СОБЫТИЕ / ТРИАТЛОН / САЙТ",
    description: "Сайт предстартового кэмпа в Сочи: программа, тренеры, условия и заявка собраны в ясный маршрут, а данные Open‑Meteo о рассвете и закате мягко меняют температуру темы.",
    timeYear: 2026,
    href: "https://hotlinecamp.ru/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/hotline-camp.mp4?v=b0efcbbba5d7",
    previewPoster: "assets/reel-posters/hotline-camp.jpg?v=cc54b4358c35",
    previewOrientation: "landscape",
    previewMeta: "СОЧИНСКАЯ ПАЛИТРА, МЕНЮ И ТРЕНЕРЫ / 00:14",
    x: 68,
    y: 54,
    size: 18,
  },
  {
    id: "dusty",
    parent: "private-practice",
    kind: "project",
    label: "DUSTY MERCH",
    mapLabel: "Интернет-магазин мерча бегового клуба Dusty\u00a0Dumbbells",
    title: "DUSTY MERCH",
    meta: "МАГАЗИН / САЙТ",
    description: "Небольшой интернет-магазин с собственной визуальной системой и быстрым запуском.",
    timeYear: 2025,
    href: "https://merch.dustydumbbells.com/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/dusty-merch.mp4?v=0a270ae1ed7f",
    previewOrientation: "landscape",
    previewMeta: "КАТАЛОГ И ОФОРМЛЕНИЕ / 00:07",
    x: 73,
    y: 61,
    size: 17,
  },
  {
    id: "dd-camp",
    parent: "private-practice",
    kind: "project",
    label: "DD CAMP",
    mapLabel: "Сайт осеннего кэмпа Dusty\u00a0Dumbbells",
    title: "DUSTY DUMBBELLS CAMP",
    meta: "СОБЫТИЕ / САЙТ",
    description: "Сайт спортивного кэмпа: программа, атмосфера события и вся практическая информация в одном месте.",
    timeYear: 2025,
    href: "https://camp.dustydumbbells.com/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/dusty-camp.mp4?v=f37879bb3bb6",
    previewOrientation: "landscape",
    previewMeta: "ПРОГРАММА И АТМОСФЕРА / 00:07",
    x: 85,
    y: 66,
    size: 15,
  },
  {
    id: "eleven",
    parent: "private-practice",
    kind: "project",
    label: "11 111",
    mapLabel: "Сайт проекта «11 111» Виктора Доронина",
    title: "11 111",
    meta: "ИСТОРИЯ / ПАРТНЁРЫ / САЙТ",
    description: "Сайт первого в мире 31-дневного ультратриатлона Виктора Доронина. Привлекаем болельщиков и партнёров.",
    timeYear: 2026,
    href: "https://11111.life/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/11111.mp4?v=a848a8f93283",
    previewPoster: "assets/reel-posters/11111.jpg?v=cb3ffc3a8d94",
    previewOrientation: "landscape",
    previewMeta: "ИСТОРИЯ, ЦЕЛЬ И МАСШТАБ / 00:12",
    x: 74,
    y: 72,
    size: 14,
  },
  {
    id: "ks-fish",
    parent: "private-practice",
    kind: "project",
    label: "KS FISH",
    mapLabel: "Сайт «Рыбной лавки капитана Селёдкина»",
    title: "KS FISH",
    meta: "КАТАЛОГ / САЙТ",
    description: "Каталожный сайт с ясной продуктовой структурой и визуальным ощущением холодного течения.",
    timeYear: 2020,
    href: "https://ks.fish/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/ks-fish.mp4?v=e8c9dd603327",
    previewOrientation: "landscape",
    previewMeta: "ВИТРИНА, ПРОДУКТ И ИСТОРИЯ / 00:08",
    x: 90,
    y: 78,
    size: 13,
  },
  {
    id: "doronin",
    parent: "private-practice",
    kind: "project",
    label: "ДОРОНИН В ДЕЛЕ",
    mapLabel: "Интернет-магазин «Доронин в деле»",
    title: "ДОРОНИН В ДЕЛЕ",
    meta: "МЕРЧ / TILDA / ЭКСПРЕСС-ЗАПУСК",
    description: "Компактная витрина мерча Виктора Доронина — с выразительной подачей и понятным сценарием заказа.",
    timeYear: 2025,
    href: "https://doronin.store/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/doronin.mp4?v=d7fb14430c80",
    previewOrientation: "landscape",
    previewMeta: "КОЛЛЕКЦИЯ И МЕРЧ / 00:07",
    x: 77,
    y: 81,
    size: 13,
  },
  {
    id: "running",
    kind: "personal",
    shape: "sphere",
    label: "БЕГ",
    title: "БЕГ",
    meta: "ЛИЧНЫЙ ЦЕНТР / ДИСТАНЦИЯ / РИТМ",
    description: "Бег — личный центр притяжения: он возвращает ритм, собранность и ощущение движения вперёд — на дистанции и вне её.",
    href: "https://www.instagram.com/stories/highlights/18054491965888038/",
    kindLabel: "ЛИЧНОЕ / ЦЕНТР ПРИТЯЖЕНИЯ",
    x: 61,
    y: 75,
    size: 60,
  },
  {
    id: "art",
    kind: "personal",
    label: "ИСКУССТВО",
    title: "ИСКУССТВО",
    meta: "КУЛЬТУРА / СМОТРЕТЬ ЗАНОВО",
    description: "Не отдельное хобби, а способ смотреть внимательнее и постоянно перенастраивать собственную оптику.",
    href: "https://garagemca.org/calendar",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 53,
    y: 81,
    size: 17,
  },
  {
    id: "football",
    kind: "personal",
    label: "ФУТБОЛ",
    title: "ФУТБОЛ",
    meta: "СМОТРЕТЬ / ЧИТАТЬ / ОБСУЖДАТЬ",
    description: "Игра, в которой интересны движение, пространство, системы и исключения из них.",
    href: "https://www.sports.ru/tribuna/blogs/vadimlukomski/2249320.html",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 43,
    y: 76,
    size: 14,
  },
  {
    id: "snow",
    kind: "personal",
    label: "СНЕГ",
    title: "СНЕГ",
    meta: "СНОУБОРД / ДВИЖЕНИЕ",
    description: "Способ переключить режим внимания и снова почувствовать скорость, склон и тело.",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 34,
    y: 69,
    size: 13,
  },
  {
    id: "music",
    kind: "personal",
    label: "МУЗЫКА",
    title: "МУЗЫКА",
    meta: "СЛУШАТЬ / ПОВТОРЯТЬ",
    description: "Постоянный фон, источник ритма и иногда самый быстрый способ изменить состояние.",
    href: "https://open.spotify.com/track/3GVkPk8mqxz0itaAriG1L7?si=233684c3f400482d",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 41,
    y: 84,
    size: 12,
  },
  {
    id: "coffee",
    kind: "personal",
    label: "КОФЕ",
    title: "КОФЕ",
    meta: "РИТУАЛ / ЧЁРНЫЙ",
    description: "Маленький ежедневный ритуал и уважительный кивок агенту Куперу.",
    href: "https://en.wikipedia.org/wiki/Dale_Cooper",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 58,
    y: 84,
    size: 10,
  },
  {
    id: "youtube",
    kind: "personal",
    shape: "sphere",
    label: "YOUTUBE",
    title: "YOUTUBE",
    meta: "ИГРЫ / КУПЛИНОВ / «ТЕНЬ ЧЕРНОБЫЛЯ»",
    description: "Люблю YouTube, особенно его игровой сегмент. Самому поиграть получается не\u00a0всегда, но\u00a0смотреть мне тоже нравится. А\u00a0это — великий Дмитрий Куплинов проходит «Тень Чернобыля». Один из\u00a0моих любимых стримов.",
    href: "https://www.youtube.com/watch?v=bkbJsunB5zY",
    linkLabel: "СМОТРЕТЬ НА\u00a0YOUTUBE",
    youtube: {
      videoId: "bkbJsunB5zY",
      title: "Дмитрий Куплинов — «Тень Чернобыля», стрим №\u00a01",
      poster: "assets/kuplinov-stalker.jpg",
    },
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 72,
    y: 82,
    size: 42,
  },
  {
    id: "wave",
    kind: "personal",
    label: "ВОЛНА",
    title: "ВОЛНА",
    meta: "МОРЕ / ГОРИЗОНТ / МАСШТАБ",
    description: "Открытый горизонт возвращает чувство масштаба и напоминает: за привычными границами всегда есть продолжение.",
    href: "https://www.instagram.com/stories/highlights/17870996476264206/",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 62,
    y: 65,
    size: 12,
  },
  {
    id: "food",
    kind: "personal",
    label: "ЕДА",
    title: "ЕДА",
    meta: "ВКУС / СЕРВИС / ДЕТАЛИ",
    description: "В «Медведе» цель сервиса формулируют без церемоний: сделать так, чтобы гостям буквально снесло крышу. Не от эффектного трюка, а от точности внимания — заметить человека, понять, что для него важно, и выстроить каждую деталь вокруг этого. Для меня здесь сходятся еда, сервис и дизайн. Любить и уважать своё дело — значит прежде всего любить и уважать себя. Отсюда — бесстрашие и желание потратить себя без остатка ради того, что тебе дорого.",
    href: "https://www.fxnetworks.com/shows/the-bear/video-extras/video/64beaaa830c49e0001e758d8",
    linkLabel: "СМОТРЕТЬ ФРАГМЕНТ",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 27,
    y: 80,
    size: 10,
  },
  // Principle descriptions are the author's source text. Keep them verbatim;
  // labels, titles and metadata may be edited independently.
  {
    id: "principle-wings",
    kind: "practice",
    label: "ДОВЕРЯТЬ КРЫЛЬЯМ",
    title: "ПТИЦА ДОВЕРЯЕТ КРЫЛЬЯМ",
    meta: "НЕОПРЕДЕЛЁННОСТЬ / ГИБКОСТЬ / РЕЗУЛЬТАТ",
    description: "Несмотря на времена — стандартные вещи перестают работать, сервисы прекращают оказывать услуги, механизмы ломаются, фундаменты рушатся, то, что раньше было очевидно и не обсуждаемо, стало неочевидно и обсуждаемо — в таких условиях задача не в том, чтобы держаться процедур, а в том чтобы перепридумывать их на лету и себя заодно (это же как раз про ту самую гибкость методологии, непрерывное сотрудничество и совершенствование). Я умею двигаться в полной неопределенности и за минимальное количество времени и денег получить результат: ведь суть не в инструментах, а опыте, навыках, знаниях и упорстве, желании делать. Мне нравится поговорка про птицу, что не боится, что ветка под ней сломается — птица доверяет крыльям.",
    kindLabel: "ПРИНЦИП / 01",
    x: 7,
    y: 41,
    size: 14,
  },
  {
    id: "principle-system",
    kind: "practice",
    label: "СИСТЕМНОСТЬ",
    title: "СИСТЕМНЫЙ ПОДХОД",
    meta: "ТЕКУЩЕЕ → ЦЕЛЕВОЕ → РАЗРЫВЫ / ДЕКОМПОЗИЦИЯ",
    description: "Всегда стремлюсь к системному подходу: декомпозирую (AS IS → TO BE → GAP MAP), раскладываю большие задачи на части, оформляю свои решения, мысли, документы в понятном виде и масштабирую лучшие практики. Умею прогнозировать проекты: выстраивать тайминг, успевать к намеченным дедлайнам, оценивать риски.",
    kindLabel: "ПРИНЦИП / 02",
    x: 14,
    y: 37,
    size: 12,
  },
  {
    id: "principle-autonomy",
    kind: "practice",
    label: "САМОСТОЯТЕЛЬНОСТЬ",
    title: "САМОСТОЯТЕЛЬНОСТЬ",
    displayTitle: "САМОСТОЯ\u00adТЕЛЬНОСТЬ",
    meta: "ПРОАКТИВНОСТЬ / УСТОЙЧИВОСТЬ / НАДЁЖНОСТЬ",
    description: "У меня все отлично с самостоятельностью — меня не нужно пушить, контролировать, я проактивно прихожу с вопросами, проблемами и идеями. Проявляю устойчивость к частой смене приоритетов и всегда сохраняю адекватность, трудоспособность, этичность и ответственность — на меня можно реально положиться и просто спокойно работать.",
    kindLabel: "ПРИНЦИП / 03",
    x: 22,
    y: 40,
    size: 11,
  },
  {
    id: "principle-terms",
    kind: "practice",
    label: "ДОКУМЕНТЫ + ФИНАНСЫ",
    title: "ДОКУМЕНТЫ И ФИНАНСЫ",
    meta: "ДОГОВОРЫ / АКТЫ / БЮДЖЕТ",
    description: "Внимателен к документам: сам составляю договоры, не пропускаю детали юридических договоренностей и вовремя закрываю все работы актами. На «ты» обращаюсь с финансами: могу оценить, спланировать бюджет проекта и контролировать его выполнение.",
    kindLabel: "ПРИНЦИП / 04",
    x: 30,
    y: 43,
    size: 10,
  },
  {
    id: "principle-goal",
    kind: "practice",
    label: "ЦЕЛЬ > ФРЕЙМВОРКИ",
    title: "ЦЕЛЬ ВАЖНЕЕ ФРЕЙМВОРКОВ",
    meta: "PMBOK / TRIPLE DIAMOND / JTBD / TDD",
    description: "В работе опираюсь на фреймворки (PMBoK, Triple Diamond от Zendesk, JTBD, test-driven design и все, что оказывается полезным в конкретный момент) и опыт, здравый смысл, идеалы, принципы и ценности. И вообще очень нравится мысль о том, что обсессия средствами производства — частый синдром отсутствия смысла своей деятельности. Когда ты четко понимаешь цель, тебе вообще не нужны фреймворки, системы приоритизации и таск-менеджеры.",
    kindLabel: "ПРИНЦИП / 05",
    x: 10,
    y: 45,
    size: 13,
  },
  {
    id: "principle-improve",
    kind: "practice",
    label: "УПРАВЛЯТЬ + УЛУЧШАТЬ",
    title: "УПРАВЛЯТЬ И УЛУЧШАТЬ",
    meta: "ПРОЕКТЫ / КОМАНДА / ПРОЦЕССЫ",
    description: "За последние несколько лет успешно управлял, координировал и руководил проектами (и командой до 10 человек) с различной степенью сложности, включая масштабные и многоэтапные, соблюдая бюджет и сроки. Постоянно внедряю новые инструменты, технологии и методологии управления проектами, обучаю команду, проактивно инициирую и поддерживаю инициативы других по улучшению процессов и повышению эффективности, что приводит к улучшению качества, оптимизации, уменьшению сроков выполнения рутинных задач и снижению стоимости их реализации. К примеру, больше дизайна сейчас делаем сами в Figma, собирая макеты и лишь на финальном этапе обращаясь к внешним арт-директорам; сменил Mailchimp на Юнисендер для всей команды: сначала освоил сам, унифицировал все шаблоны писем, а затем обучил коллег работе в новом инструменте — по итогу письма собираем быстрее и растим OR, а затраты на сервис снизил в 4 раза.",
    kindLabel: "ПРИНЦИП / 06",
    x: 18,
    y: 43,
    size: 12,
  },
  {
    id: "principle-communicate",
    kind: "practice",
    label: "ЛИДЕР + КОММУНИКАТОР",
    title: "ЛИДЕР И КОММУНИКАТОР",
    displayTitle: "ЛИДЕР\nИ\u00a0КОММУНИ-\nКАТОР",
    meta: "ДОГОВАРИВАТЬСЯ / МОТИВИРОВАТЬ / АРГУМЕНТИРОВАТЬ",
    description: "Я лидер и уверенный коммуникатор — легко могу договариваться с внешними людьми и замотивировать свою команду. Коммуникабелен: могу уверенно рассказать о результате работ, работать с возражениями и аргументировать свою позицию независимо от того, с кем общаюсь.",
    kindLabel: "ПРИНЦИП / 07",
    x: 26,
    y: 55,
    size: 12,
  },
  {
    id: "principle-own",
    kind: "practice",
    label: "БРАТЬ ОТВЕТСТВЕННОСТЬ",
    title: "РЕШЕНИЕ И ОТВЕТСТВЕННОСТЬ",
    displayTitle: "РЕШЕНИЕ\nИ\u00a0ОТВЕТСТВЕН-\nНОСТЬ",
    meta: "РЕШЕНИЕ / ОТВЕТСТВЕННОСТЬ / ХЛАДНОКРОВИЕ",
    description: "Не боюсь принимать решения и брать на себя ответственность за них. Понимаю, что нет нерешаемых задач и в любой ситуации остаюсь хладнокровным.",
    kindLabel: "ПРИНЦИП / 08",
    x: 35,
    y: 54,
    size: 11,
  },
  {
    id: "principle-learn",
    kind: "practice",
    label: "УЧИТЬСЯ + ЗАМЕЧАТЬ",
    title: "УЧИТЬСЯ И ВЕРИТЬ В ДЕТАЛИ",
    meta: "УЧИТЬСЯ / НАБЛЮДАТЬ / НАХОДИТЬ",
    description: "Люблю учиться и с энтузиазмом развиваю новые умения и навыки. Оперативно нахожу нужную информацию, внимательно наблюдаю и верю в силу деталей.",
    kindLabel: "ПРИНЦИП / 09",
    x: 7,
    y: 58,
    size: 10,
  },
  {
    id: "principle-ideas",
    kind: "practice",
    label: "ИДЕИ + ТРЕНДЫ",
    title: "КРЕАТИВНЫЕ ИДЕИ И ТРЕНДЫ",
    meta: "ЦИФРОВАЯ СРЕДА / МЕДИА / ТЕХНОЛОГИИ",
    description: "Обладаю способностью быстро генерировать креативные идеи и решения. Слежу за цифровыми- и медиа-трендами, развивающимися технологиями и платформами.",
    kindLabel: "ПРИНЦИП / 10",
    x: 15,
    y: 57,
    size: 11,
  },
  {
    id: "principle-language",
    kind: "practice",
    label: "РУССКИЙ ЯЗЫК",
    title: "ГРАМОТНЫЙ РУССКИЙ ЯЗЫК",
    meta: "ЦИФРОВОЙ ЭТИКЕТ / ПУНКТУАЦИЯ / ГРАММАТИКА",
    description: "Неустанно оттачиваю грамотный русский язык: цифровой этикет, пунктуацию и грамматику.",
    kindLabel: "ПРИНЦИП / 11",
    x: 22,
    y: 60,
    size: 9,
  },
  {
    id: "principle-tools",
    kind: "practice",
    label: "БЫСТРО НАЙТИ ПОДХОД",
    title: "БЫСТРО НАЙТИ ПОДХОД",
    meta: "FIGMA / NOTION / КОД / ИИ / И ДАЛЬШЕ",
    description: "На «ты» с Figma, Photoshop, Notion, Trello, Jira, MailChimp, UniSender, Tilda, Readymag, Webflow, Miro, FigJam, JSON, HTML, большими языковыми моделями и нейросетями — а с чем еще нет, то гарантированно быстро найду к этому подход.",
    kindLabel: "ПРИНЦИП / 12",
    x: 31,
    y: 58,
    size: 10,
  },
  {
    id: "principle-now",
    kind: "practice",
    label: "НОВОЕ — СЕЙЧАС",
    title: "НОВОЕ — ПРЯМО СЕЙЧАС",
    meta: "ИННОВАЦИИ / OPENAI / ПОВСЕДНЕВНАЯ РАБОТА",
    description: "Инновации: беру все новое и лучшее и применяю прямо сейчас в повседневных задачах — вижу именно в этом смысл своей работы. Например, с продуктами OpenAI применяю два принципа: принцип первый — нельзя не использовать ChatGPT; принцип второй — участие ChatGPT не должно быть заметно.",
    kindLabel: "ПРИНЦИП / 13",
    x: 10,
    y: 68,
    size: 11,
  },
  {
    id: "principle-data-intuition",
    kind: "practice",
    label: "ЦИФРЫ + ИНТУИЦИЯ",
    title: "АНАЛИТИКА И ИНТУИЦИЯ",
    meta: "ДАННЫЕ / ВПЕЧАТЛЕНИЯ / ДОСТУПНОСТЬ",
    description: "C одной стороны считаю, что лучшие менеджеры — это аналитики, которые лучше всех на цифрах понимают как работает продукт, и имеют огромное желание свои исследования превратить в реальные продуктовые изменения и стараюсь это качество в себе развить. С другой стороны не понимаю, как можно придумать классный продукт на A/B-тестах и фокус-группах. На них можно сделать классный продукт на 2% лучше, а плохой продукт не улучшат никакие тесты. Поэтому занимаясь созданием чего-то, придумыванием, думаю не цифрами, а интуицией (Эндрю Чен вот здесь пишет о том, что управлять на основе данных — сложная и часто невозможная задача) — думаю о дизайне впечатлений и снижении стоимости взаимодействия, доступности (быть дружелюбными и демократизировать технологии для людей, фокусироваться на человеческих потребностях и мотивах), идеалах, принципах и ценностях. Цифры не предскажут трепета и возбуждения, которые возникают в душе от хорошей идеи.",
    kindLabel: "ПРИНЦИП / 14",
    x: 18,
    y: 67,
    size: 13,
  },
  {
    id: "principle-design-engineering",
    kind: "practice",
    label: "ДИЗАЙН-ИНЖЕНЕР",
    title: "ДИЗАЙН-ИНЖЕНЕР",
    meta: "ДИЗАЙН / КОД / РАБОЧИЙ ПРОТОТИП",
    description: "Мехмет Байтас написал о дизайн-инженерах — универсальных специалистах, которые сочетают в себе навыки и дизайнера, и разработчика. Они могут самостоятельно спроектировать дизайн и довести его до рабочего прототипа, написав код. Вот всегда думаю и о себе в таком ключе: одновременно чувствую и композицию, и технические ограничения.",
    kindLabel: "ПРИНЦИП / 15",
    x: 27,
    y: 66,
    size: 14,
  },
  {
    id: "principle-shaper",
    kind: "practice",
    label: "СКУЛЬПТОР / АРХЕОЛОГ",
    title: "СКУЛЬПТОР / АРХЕОЛОГ",
    meta: "ПРИДАТЬ ФОРМУ / УБРАТЬ ЛИШНЕЕ / НАЙТИ ЦЕННОСТЬ",
    description: "Я встречал еще пару метафор своего подхода к работе. Иногда такая роль называется «shaper» (придающий форму): подобно скульптору, вы постепенно откалываете лишнее, чтобы оставить суть. Еще один вариант — сравнение с работой археолога; в отличие от скульптора, вы не принимаете творческих решений: нужная людям ценность уже хранится под толщей земли, и нужно методично убирать лишнее, не задевая важного.",
    kindLabel: "ПРИНЦИП / 16",
    x: 38,
    y: 64,
    size: 12,
  },
  {
    id: "principle-experiment",
    kind: "practice",
    label: "ГОСТЕПРИИМСТВО + ЗАБОТА",
    title: "ЦИФРОВОЕ ГОСТЕПРИИМСТВО И ЗАБОТА",
    displayTitle: "ЦИФРОВОЕ\nГОСТЕПРИИМ-\nСТВО И ЗАБОТА",
    meta: "CX / IXD / ИНКЛЮЗИВНОСТЬ / ГЕНЕРАТИВНЫЙ ИИ",
    description: "Области интереса сейчас: CX и IxD — «цифровое» гостеприимство и забота, как я понимаю их, инклюзивные практики в веб-дизайне и веб-продакшне. Генеративный искусственный интеллект в контексте этих точек интереса. Мне всегда было интересно то, чем занимаются люди на позициях «продакт-проджект-гроус-хакеров» или «ченджеров» — создавать внутри компании то, чего еще не было: Такие проекты не всегда про IT, не по должностной инструкции, не будут оплачены отдельно, но мне интересно это сделать, потому что это кажется возможным и важным, новым. Если говорить тут о «работодателе / проекте мечты», то хотелось бы быть частью компании, которая осознает важность экспериментов и дает экспериментировать «легально».",
    kindLabel: "ПРИНЦИП / 17",
    x: 20,
    y: 77,
    size: 14,
  },
];

export {
  mapItems,
  principlesSourceHref,
  reelChapterSources,
};
