// Runtime layer 3/6: deterministic portfolio map data.
const principlesSourceHref = "https://app.notion.com/p/digital-web-digital-f68fc13247614ccb9738d9a85acf29b4?source=copy_link#70405c2623e342fb98d027c8634f2207";

const mapItems = [
  {
    id: "garage",
    kind: "company",
    label: "МУЗЕЙ «ГАРАЖ»",
    title: "МУЗЕЙ «ГАРАЖ»",
    meta: "ОКТ 2021—МАР 2025 / СТАРШИЙ МЕНЕДЖЕР ВЕБ-РАЗРАБОТКИ",
    description: "Самый важный профессиональный период: здесь сошлись культура, продукт, исследования, дизайн и большая веб-разработка.",
    evidence: {
      task: "Развивать цифровые продукты Музея — от исследования до релиза.",
      role: "Старший менеджер web-разработки: исследования, delivery, подрядчики и бюджеты.",
      result: "2021—2025: связанный портфель сайтов, архивов, курсов и инклюзивного приложения.",
    },
    timeYear: 2023,
    timeLabel: "2021—2025",
    href: "https://garagemca.org/ru",
    kindLabel: "ИНСТИТУЦИЯ / 2021—2025",
    x: 46,
    y: 14,
    size: 76,
  },
  {
    id: "private-practice",
    kind: "project",
    accentKind: "practice",
    label: "ЧАСТНАЯ ПРАКТИКА",
    title: "ЧАСТНАЯ ПРАКТИКА",
    meta: "СЕЙЧАС / НЕБОЛЬШИЕ ЦИФРОВЫЕ ПРОЕКТЫ",
    description: "Самостоятельная работа с проектами, которым нужно быстро разобраться в задаче, придать форму и дойти до запуска.",
    evidence: {
      task: "Быстро придавать цифровую форму небольшим проектам и доводить их до запуска.",
      role: "Полный цикл: исследование, концепция, прототип, дизайн, сборка, домен и сопровождение.",
      result: "Самостоятельная линейка сайтов, сервисов и магазинов — от Tarski до Shirokostup и Herman.",
    },
    timeYear: 2023,
    timeLabel: "2020—СЕЙЧАС",
    kindLabel: "ПРАКТИКА / СВЯЗУЮЩИЙ УЗЕЛ",
    x: 61,
    y: 43,
    size: 38,
  },
  {
    id: "optimal",
    kind: "company",
    label: "ОПТИМАЛГРУПП",
    title: "ЦИФРОВОЕ АГЕНТСТВО «ОПТИМАЛГРУПП»",
    meta: "РАННИЙ ОПЫТ / ЦИФРОВОЕ АГЕНТСТВО",
    description: "Клиентские web-проекты, производство, коммуникация и ранний опыт работы на стыке задач и команд.",
    timeYear: 2025.5,
    timeLabel: "2025—2026",
    kindLabel: "КОМПАНИЯ / АГЕНТСТВО",
    x: 24,
    y: 18,
    size: 29,
  },
  {
    id: "ilmix",
    kind: "company",
    label: "ИЛЬМИКСГРУПП",
    title: "«ИЛЬМИКСГРУПП»",
    meta: "ПОЧТИ 5 ЛЕТ / ЦИФРОВОЕ НАПРАВЛЕНИЕ",
    description: "Почти пять лет digital-работы внутри фармацевтической компании: развитие внутренних web-направлений и продуктов, которые позднее исчезли вместе с самостоятельной компанией.",
    timeYear: 2018.5,
    timeLabel: "2017—2020",
    kindLabel: "КОМПАНИЯ / ВНУТРЕННЯЯ КОМАНДА",
    x: 16,
    y: 30,
    size: 38,
  },
  {
    id: "garage-site",
    parent: "garage",
    kind: "project",
    label: "САЙТ МУЗЕЯ",
    title: "САЙТ МУЗЕЯ «ГАРАЖ»",
    meta: "UX / UI / ДИЗАЙН-ИНЖИНИРИНГ / ВЕБ-МЕНЕДЖМЕНТ",
    description: "Исследование, развитие и ежедневная работа с главным цифровым продуктом Музея и его командой.",
    timeYear: 2023,
    timeLabel: "2021—2025",
    href: "https://garagemca.org/",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-site.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "ГЛАВНАЯ, КАЛЕНДАРЬ И МЕДИА / 00:08",
    x: 58,
    y: 14,
    size: 23,
  },
  {
    id: "narkomfin",
    parent: "garage",
    kind: "project",
    label: "ДОМ НАРКОМФИНА",
    title: "ДОМ НАРКОМФИНА",
    meta: "ДИЗАЙН / UX / UI / ЦИФРОВОЙ ОПЫТ",
    description: "Дизайн сайта Дома Наркомфина — от интерактивной модели здания и световых состояний до календаря и цельной цифровой навигации.",
    evidence: {
      task: "Собрать цельный цифровой опыт институционального и исследовательского проекта.",
      role: "Менеджмент, UX/UI-исследование, дизайн-инжиниринг и координация разработки.",
      result: "MVP за вечер и рабочий день; после полного запуска — 51 420 уникальных посетителей и 67 893 визита за июль—ноябрь 2023.",
    },
    timeYear: 2023,
    timeLabel: "2023",
    href: "https://narkomfin.ru/",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/narkomfin.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "ДИЗАЙН И ВЕБ-РАЗРАБОТКА / 00:08",
    x: 67,
    y: 21,
    size: 25,
  },
  {
    id: "collection",
    parent: "garage",
    kind: "project",
    label: "КОЛЛЕКЦИЯ",
    title: "КОЛЛЕКЦИЯ И ОТКРЫТОЕ ХРАНЕНИЕ",
    meta: "2024 / ПРОДУКТ / ИССЛЕДОВАНИЕ / ЗАПУСК",
    description: "Запуск каталога коллекции и открытого хранения: продуктовая логика, исследования, интерфейс и координация реализации.",
    evidence: {
      task: "Каталогизировать коллекцию и связать онлайн-каталог с открытым хранением.",
      role: "Продуктовая логика, исследование, интерфейс и координация реализации.",
      result: "Запущены каталог, страницы авторов и работ, а также сценарии подготовки к посещению.",
    },
    timeYear: 2024,
    timeLabel: "2024",
    href: "https://garagemca.org/collection/catalogue",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-collection.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "КАТАЛОГ И ОТКРЫТОЕ ХРАНЕНИЕ / 00:08",
    x: 75,
    y: 19,
    size: 22,
  },
  {
    id: "garage-archives",
    parent: "garage",
    kind: "project",
    label: "АРХИВЫ",
    title: "АРХИВНЫЕ ПРОЕКТЫ",
    meta: "АРХИВ РОССИЙСКОГО ИСКУССТВА / I-M-I / NNS",
    description: "Поддержка и развитие цифровых архивов — от повседневных задач до проектирования новых сценариев доступа к материалам.",
    href: "https://russianartarchive.net/ru",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    x: 59,
    y: 28,
    size: 18,
  },
  {
    id: "garage-courses",
    parent: "garage",
    kind: "project",
    label: "ОНЛАЙН-КУРСЫ",
    title: "ОНЛАЙН-КУРСЫ МУЗЕЯ",
    meta: "ОБУЧЕНИЕ / ПРОДУКТ / ПАРТНЁРСТВА",
    description: "Бесплатные образовательные продукты: запуск курсов, улучшение сценариев и работа с партнёрами.",
    href: "https://garagemca.org/learn/online-courses",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-courses.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "КУРСЫ И УЧЕБНЫЕ СЦЕНАРИИ / 00:07",
    x: 80,
    y: 30,
    size: 17,
  },
  {
    id: "garage-app",
    parent: "garage",
    kind: "project",
    label: "Я ИДУ В МУЗЕЙ",
    title: "«Я ИДУ В МУЗЕЙ»",
    meta: "ДОСТУПНОСТЬ / МОБИЛЬНЫЙ ПРОДУКТ / ПЕРЕЗАПУСК",
    description: "Перезапуск приложения для людей с ментальными особенностями и их близких: доступность, навигация и понятный маршрут.",
    evidence: {
      task: "Сделать подготовку к музею понятной людям с ментальными особенностями и их близким.",
      role: "IxD/UX/UI-исследование и проектирование маршрутов.",
      result: "Перезапущены нативные iOS/Android-приложения с материалами о доступности, путеводителями и играми.",
    },
    timeYear: 2024,
    timeLabel: "2024",
    href: "https://apps.apple.com/ru/app/я-иду-в-музей/id1558275984",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    x: 84,
    y: 36,
    size: 17,
  },
  {
    id: "garage-webzine",
    parent: "garage",
    kind: "project",
    label: "ВЕБ-ЗИН",
    title: "«НЕЧЕЛОВЕЧЕСКИЕ ЖИВОТНЫЕ И ТЕХНИКА»",
    meta: "ИССЛЕДОВАНИЕ / ДИЗАЙН-ИНЖИНИРИНГ / КОД",
    description: "Небольшой исследовательский web-зин, собранный руками как самостоятельная цифровая форма.",
    href: "https://non-human-animals.garage.digital/index.html",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    previewVideo: "assets/reels/garage-webzine.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "ТЕМА, ТЕКСТ И ИНТЕРАКТИВ / 00:08",
    x: 72,
    y: 34,
    size: 15,
  },
  {
    id: "garage-institutions",
    parent: "garage",
    kind: "project",
    label: "ПОМОЩЬ ИНСТИТУЦИЯМ",
    title: "ПОМОЩЬ КУЛЬТУРНЫМ ИНСТИТУЦИЯМ",
    meta: "КОНСУЛЬТАЦИИ / ДИЗАЙН / ТЕХНИЧЕСКАЯ ПОМОЩЬ",
    description: "Знания, консультации и конкретная техническая помощь культурным институциям и НКО — с акцентом на быстрый запуск.",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    x: 55,
    y: 37,
    size: 16,
  },
  {
    id: "garage-endowment",
    parent: "garage",
    kind: "project",
    label: "ЭНДАУМЕНТ",
    title: "ЭНДАУМЕНТ-ФОНД МУЗЕЯ",
    meta: "ПОДДЕРЖКА / РАЗВИТИЕ / КОНТЕНТ",
    description: "Поддержка и развитие отдельного цифрового продукта эндаумент-фонда Музея.",
    href: "https://endowment.garagemca.org/ru/",
    kindLabel: "ПРОЕКТ / ГРАФ «ГАРАЖА»",
    x: 53,
    y: 26,
    size: 12,
  },
  {
    id: "shirokostup",
    parent: "private-practice",
    kind: "project",
    label: "SHIROKOSTUP",
    mapLabel: "Сайт независимого куратора и исследователя Ольги Широкоступ",
    title: "SHIROKOSTUP",
    meta: "РЕДАКЦИОННЫЙ ДИЗАЙН / САЙТ / 2026",
    description: "Портфолио куратора и исследовательницы: редакционная структура, спокойный интерфейс и самостоятельный\u00a0запуск.",
    evidence: {
      task: "Превратить кураторскую практику и архив в читаемое портфолио.",
      role: "Редакционная структура, дизайн, разработка и запуск.",
      result: "Запущен самостоятельный сайт с архивом проектов и устойчивыми активными и архивными состояниями.",
    },
    timeYear: 2026,
    timeLabel: "2026",
    href: "https://shirokostup.site/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/shirokostup.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "ПОРТФОЛИО И АРХИВ ПРОЕКТОВ / 00:07",
    x: 82,
    y: 52,
    size: 22,
  },
  {
    id: "tarski",
    parent: "private-practice",
    kind: "project",
    label: "TARSKI",
    mapLabel: "Сайт среды изучения и поддержки социально ориентированного и вовлекающего искусства Tarski",
    title: "TARSKI",
    meta: "ЦИФРОВОЙ ПРОДУКТ / САЙТ",
    description: "Цифровой продукт и web-система: продуктовая логика, интерфейс и последовательное развитие.",
    evidence: {
      task: "Собрать цифровую среду для социально ориентированного и вовлекающего искусства.",
      role: "Продуктовая логика, дизайн-система, реализация и доступность.",
      result: "Запущена адаптивная web-система с программой, сообществом и полноценным мобильным маршрутом.",
    },
    timeYear: 2026,
    timeLabel: "2026",
    href: "https://tarski.ru/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/tarski.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "СООБЩЕСТВО И ПРОГРАММА / 00:08",
    x: 78,
    y: 47,
    size: 23,
  },
  {
    id: "herman",
    parent: "private-practice",
    kind: "project",
    label: "HERMAN & CO",
    mapLabel: "Сайт стилиста и эксперта по уходу Германа Винокурова",
    title: "HERMAN & CO",
    meta: "СЕРВИС / САЙТ",
    description: "Сервисный сайт с живым статусом, ясной записью и одной цельной системой материалов и состояний.",
    evidence: {
      task: "Собрать сервисный сайт, который ведёт к записи без лишних шагов.",
      role: "Сценарий, единая материальная система, дизайн и реализация.",
      result: "Запущен сайт с живым статусом, ясными услугами и прямой записью.",
    },
    timeYear: 2026,
    timeLabel: "2026",
    href: "https://barberherman.ru/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/herman.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "СТАТУС, УСЛУГИ И ЗАПИСЬ / 00:07",
    x: 82,
    y: 58,
    size: 19,
  },
  {
    id: "dusty",
    parent: "private-practice",
    kind: "project",
    label: "DUSTY MERCH",
    mapLabel: "Интернет-магазин мерча бегового клуба Dusty\u00a0Dumbbells",
    title: "DUSTY MERCH",
    meta: "МАГАЗИН / САЙТ",
    description: "Небольшой commerce-проект с самостоятельной визуальной системой и быстрым запуском.",
    href: "https://merch.dustydumbbells.com/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/dusty-merch.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "КАТАЛОГ И ОФОРМЛЕНИЕ / 00:07",
    x: 73,
    y: 61,
    size: 17,
  },
  {
    id: "dd-camp",
    parent: "private-practice",
    kind: "project",
    label: "DD CAMP",
    mapLabel: "Сайт осеннего кэмпа Dusty\u00a0Dumbbells",
    title: "DUSTY DUMBBELLS CAMP",
    meta: "СОБЫТИЕ / САЙТ",
    description: "Сайт спортивного кемпа: структура программы, атмосфера события и практичная точка входа.",
    href: "https://camp.dustydumbbells.com/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/dusty-camp.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "ПРОГРАММА И АТМОСФЕРА / 00:07",
    x: 85,
    y: 66,
    size: 15,
  },
  {
    id: "eleven",
    parent: "private-practice",
    kind: "project",
    label: "11 111",
    mapLabel: "Сайт проекта «11 111» Виктора Доронина",
    title: "11 111",
    meta: "БРЕНД / САЙТ",
    description: "Небольшой брендовый web-проект, где цифровая форма работает как самостоятельный характер.",
    href: "https://11111.life/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/11111.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "ИСТОРИЯ, ЦЕЛЬ И МАСШТАБ / 00:08",
    x: 74,
    y: 72,
    size: 14,
  },
  {
    id: "ks-fish",
    parent: "private-practice",
    kind: "project",
    label: "KS FISH",
    mapLabel: "Сайт «Рыбной лавки капитана Селедкина»",
    title: "KS FISH",
    meta: "КАТАЛОГ / САЙТ",
    description: "Каталожный сайт с ясной продуктовой структурой и визуальным ощущением холодного течения.",
    href: "https://ks.fish/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/ks-fish.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "ВИТРИНА, ПРОДУКТ И ИСТОРИЯ / 00:08",
    x: 90,
    y: 78,
    size: 13,
  },
  {
    id: "doronin",
    parent: "private-practice",
    kind: "project",
    label: "DORONIN",
    mapLabel: "Интернет-магазин мерча Виктора Доронина",
    title: "DORONIN",
    meta: "МАГАЗИН / САЙТ",
    description: "Цифровой магазин с компактной, собранной и понятной системой взаимодействия.",
    href: "https://doronin.store/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/doronin.mp4?v=20260728-landscape-reels-1",
    previewOrientation: "landscape",
    previewMeta: "КОЛЛЕКЦИЯ И МЕРЧ / 00:07",
    x: 77,
    y: 81,
    size: 13,
  },
  {
    id: "running",
    kind: "personal",
    label: "БЕГ",
    title: "БЕГ",
    meta: "ЛИЧНЫЙ ЦЕНТР / ДИСТАНЦИЯ / РИТМ",
    description: "Бег — личный центр притяжения: он возвращает ритм, собранность и ощущение движения вперёд — на дистанции и вне её.",
    href: "https://www.instagram.com/stories/highlights/18054491965888038/",
    kindLabel: "ЛИЧНОЕ / ЦЕНТР ПРИТЯЖЕНИЯ",
    x: 61,
    y: 75,
    size: 60,
  },
  {
    id: "art",
    kind: "personal",
    label: "ИСКУССТВО",
    title: "ИСКУССТВО",
    meta: "КУЛЬТУРА / СМОТРЕТЬ ЗАНОВО",
    description: "Не отдельное хобби, а способ смотреть внимательнее и постоянно перенастраивать собственную оптику.",
    href: "https://garagemca.org/calendar",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 53,
    y: 81,
    size: 17,
  },
  {
    id: "football",
    kind: "personal",
    label: "ФУТБОЛ",
    title: "ФУТБОЛ",
    meta: "СМОТРЕТЬ / ЧИТАТЬ / ОБСУЖДАТЬ",
    description: "Игра, в которой интересны движение, пространство, системы и исключения из них.",
    href: "https://www.sports.ru/tribuna/blogs/vadimlukomski/2249320.html",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 43,
    y: 76,
    size: 14,
  },
  {
    id: "snow",
    kind: "personal",
    label: "СНЕГ",
    title: "СНЕГ",
    meta: "СНОУБОРД / ДВИЖЕНИЕ",
    description: "Способ переключить режим внимания и снова почувствовать скорость, склон и тело.",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 34,
    y: 69,
    size: 13,
  },
  {
    id: "music",
    kind: "personal",
    label: "МУЗЫКА",
    title: "МУЗЫКА",
    meta: "СЛУШАТЬ / ПОВТОРЯТЬ",
    description: "Постоянный фон, источник ритма и иногда самый быстрый способ изменить состояние.",
    href: "https://open.spotify.com/track/3GVkPk8mqxz0itaAriG1L7?si=233684c3f400482d",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 41,
    y: 84,
    size: 12,
  },
  {
    id: "coffee",
    kind: "personal",
    label: "КОФЕ",
    title: "КОФЕ",
    meta: "РИТУАЛ / ЧЁРНЫЙ",
    description: "Маленький ежедневный ритуал и уважительный кивок агенту Куперу.",
    href: "https://en.wikipedia.org/wiki/Dale_Cooper",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 58,
    y: 84,
    size: 10,
  },
  {
    id: "wave",
    kind: "personal",
    label: "ВОЛНА",
    title: "ВОЛНА",
    meta: "МОРЕ / ГОРИЗОНТ / МАСШТАБ",
    description: "Открытый горизонт возвращает чувство масштаба и напоминает: за привычными границами всегда есть продолжение.",
    href: "https://www.instagram.com/stories/highlights/17870996476264206/",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 62,
    y: 65,
    size: 12,
  },
  {
    id: "food",
    kind: "personal",
    label: "ЕДА",
    title: "ЕДА",
    meta: "ВКУС / МЕСТА / ДЕТАЛИ",
    description: "От суши до пастрами: вкус — ещё один способ замечать детали и запоминать места.",
    href: "https://daily.afisha.ru/eating/1771-luchshaya-pastrami-v-moskve/",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 27,
    y: 80,
    size: 10,
  },
  {
    id: "principle-wings",
    kind: "practice",
    label: "ДОВЕРЯТЬ КРЫЛЬЯМ",
    title: "ПТИЦА ДОВЕРЯЕТ КРЫЛЬЯМ",
    meta: "НЕОПРЕДЕЛЁННОСТЬ / ГИБКОСТЬ / РЕЗУЛЬТАТ",
    description: "Когда привычные сервисы и механизмы перестают работать, не держусь за процедуру: быстро пересобираю её под новую реальность. Умею двигаться в неопределённости и получать результат при ограниченных времени и бюджете. Как птица не боится сломанной ветки, потому что доверяет крыльям, так я опираюсь на опыт, знания и упорство.",
    kindLabel: "ПРИНЦИП / 01",
    x: 7,
    y: 41,
    size: 14,
  },
  {
    id: "principle-system",
    kind: "practice",
    label: "СИСТЕМНОСТЬ",
    title: "СИСТЕМНЫЙ ПОДХОД",
    meta: "ТЕКУЩЕЕ → ЦЕЛЕВОЕ → РАЗРЫВЫ / ДЕКОМПОЗИЦИЯ",
    description: "Фиксирую текущее и целевое состояние, нахожу разрывы, раскладываю большие задачи на части и оформляю решения так, чтобы их можно было повторить и масштабировать. Планирую сроки, оцениваю риски и довожу проект до результата.",
    kindLabel: "ПРИНЦИП / 02",
    x: 14,
    y: 37,
    size: 12,
  },
  {
    id: "principle-autonomy",
    kind: "practice",
    label: "САМОСТОЯТЕЛЬНОСТЬ",
    title: "САМОСТОЯТЕЛЬНОСТЬ",
    meta: "ПРОАКТИВНОСТЬ / УСТОЙЧИВОСТЬ / НАДЁЖНОСТЬ",
    description: "Работаю самостоятельно: мне не нужен постоянный контроль. Сам прихожу с вопросами, проблемами и идеями, спокойно переживаю смену приоритетов и сохраняю работоспособность, этичность и ответственность. На меня можно положиться.",
    kindLabel: "ПРИНЦИП / 03",
    x: 22,
    y: 40,
    size: 11,
  },
  {
    id: "principle-terms",
    kind: "practice",
    label: "ДОКУМЕНТЫ + ФИНАНСЫ",
    title: "ДОКУМЕНТЫ И ФИНАНСЫ",
    meta: "ДОГОВОРЫ / АКТЫ / БЮДЖЕТ",
    description: "Сам составляю договоры, не пропускаю детали юридических договорённостей и вовремя закрываю работы актами. Умею оценить и спланировать бюджет проекта, а затем контролировать его выполнение.",
    kindLabel: "ПРИНЦИП / 04",
    x: 30,
    y: 43,
    size: 10,
  },
  {
    id: "principle-goal",
    kind: "practice",
    label: "ЦЕЛЬ > ФРЕЙМВОРКИ",
    title: "ЦЕЛЬ ВАЖНЕЕ ФРЕЙМВОРКОВ",
    meta: "PMBOK / TRIPLE DIAMOND / JTBD / TDD",
    description: "Использую PMBOK, Triple Diamond, JTBD, разработку через тестирование и другие полезные методы, но не превращаю их в цель. Когда смысл и результат определены ясно, опыт и здравый смысл важнее очередной системы приоритизации или диспетчера задач.",
    kindLabel: "ПРИНЦИП / 05",
    x: 10,
    y: 45,
    size: 13,
  },
  {
    id: "principle-improve",
    kind: "practice",
    label: "УПРАВЛЯТЬ + УЛУЧШАТЬ",
    title: "УПРАВЛЯТЬ И УЛУЧШАТЬ",
    meta: "ПРОЕКТЫ / КОМАНДА / ПРОЦЕССЫ",
    description: "Управлял многоэтапными проектами и командой до 10 человек, соблюдая сроки и бюджет. Улучшаю процессы, осваиваю инструменты и обучаю коллег: так мы перенесли больше дизайна внутрь команды, ускорили сборку рассылок и в четыре раза снизили стоимость сервиса.",
    kindLabel: "ПРИНЦИП / 06",
    x: 18,
    y: 43,
    size: 12,
  },
  {
    id: "principle-communicate",
    kind: "practice",
    label: "ЛИДЕР + КОММУНИКАТОР",
    title: "ЛИДЕР И КОММУНИКАТОР",
    meta: "ДОГОВАРИВАТЬСЯ / МОТИВИРОВАТЬ / АРГУМЕНТИРОВАТЬ",
    description: "Договариваюсь с внешними партнёрами и помогаю команде двигаться к результату. Умею ясно представить работу, услышать возражения и аргументировать позицию независимо от аудитории.",
    kindLabel: "ПРИНЦИП / 07",
    x: 26,
    y: 55,
    size: 12,
  },
  {
    id: "principle-own",
    kind: "practice",
    label: "БРАТЬ ОТВЕТСТВЕННОСТЬ",
    title: "РЕШЕНИЕ И ОТВЕТСТВЕННОСТЬ",
    meta: "РЕШЕНИЕ / ОТВЕТСТВЕННОСТЬ / ХЛАДНОКРОВИЕ",
    description: "Не боюсь принимать решения и брать на себя ответственность за них. Понимаю, что нет нерешаемых задач, и в любой ситуации остаюсь хладнокровным.",
    kindLabel: "ПРИНЦИП / 08",
    x: 35,
    y: 54,
    size: 11,
  },
  {
    id: "principle-learn",
    kind: "practice",
    label: "УЧИТЬСЯ + ЗАМЕЧАТЬ",
    title: "УЧИТЬСЯ И ВЕРИТЬ В ДЕТАЛИ",
    meta: "УЧИТЬСЯ / НАБЛЮДАТЬ / НАХОДИТЬ",
    description: "Люблю учиться и с энтузиазмом развиваю новые умения и навыки. Оперативно нахожу нужную информацию, внимательно наблюдаю и верю в силу деталей.",
    kindLabel: "ПРИНЦИП / 09",
    x: 7,
    y: 58,
    size: 10,
  },
  {
    id: "principle-ideas",
    kind: "practice",
    label: "ИДЕИ + ТРЕНДЫ",
    title: "КРЕАТИВНЫЕ ИДЕИ И ТРЕНДЫ",
    meta: "ЦИФРОВАЯ СРЕДА / МЕДИА / ТЕХНОЛОГИИ",
    description: "Быстро генерирую идеи и решения. Слежу за цифровыми и медиатрендами, развивающимися технологиями и платформами.",
    kindLabel: "ПРИНЦИП / 10",
    x: 15,
    y: 57,
    size: 11,
  },
  {
    id: "principle-language",
    kind: "practice",
    label: "РУССКИЙ ЯЗЫК",
    title: "ГРАМОТНЫЙ РУССКИЙ ЯЗЫК",
    meta: "ЦИФРОВОЙ ЭТИКЕТ / ПУНКТУАЦИЯ / ГРАММАТИКА",
    description: "Неустанно оттачиваю грамотный русский язык: цифровой этикет, пунктуацию и грамматику.",
    kindLabel: "ПРИНЦИП / 11",
    x: 22,
    y: 60,
    size: 9,
  },
  {
    id: "principle-tools",
    kind: "practice",
    label: "БЫСТРО НАЙТИ ПОДХОД",
    title: "БЫСТРО НАЙТИ ПОДХОД",
    meta: "FIGMA / NOTION / КОД / ИИ / И ДАЛЬШЕ",
    description: "На «ты» с Figma, Photoshop, Notion, Trello, Jira, MailChimp, UniSender, Tilda, Readymag, Webflow, Miro, FigJam, JSON, HTML, большими языковыми моделями и нейросетями — а с чем ещё нет, то гарантированно быстро найду к этому подход.",
    kindLabel: "ПРИНЦИП / 12",
    x: 31,
    y: 58,
    size: 10,
  },
  {
    id: "principle-now",
    kind: "practice",
    label: "НОВОЕ — СЕЙЧАС",
    title: "НОВОЕ — ПРЯМО СЕЙЧАС",
    meta: "ИННОВАЦИИ / OPENAI / ПОВСЕДНЕВНАЯ РАБОТА",
    description: "Беру полезное новое и сразу проверяю его в повседневной работе. Для продуктов OpenAI держу два правила: нельзя игнорировать возможности ChatGPT, но его участие не должно быть заметнее качества результата.",
    kindLabel: "ПРИНЦИП / 13",
    x: 10,
    y: 68,
    size: 11,
  },
  {
    id: "principle-data-intuition",
    kind: "practice",
    label: "ЦИФРЫ + ИНТУИЦИЯ",
    title: "АНАЛИТИКА И ИНТУИЦИЯ",
    meta: "ДАННЫЕ / ВПЕЧАТЛЕНИЯ / ДОСТУПНОСТЬ",
    description: "Данные помогают понять продукт и превратить наблюдения в изменения, но не заменяют замысел. Тесты способны улучшить сильное решение, однако не придумают его. Поэтому соединяю аналитику с интуицией, проектированием впечатлений, доступностью и вниманием к человеческим мотивам.",
    kindLabel: "ПРИНЦИП / 14",
    x: 18,
    y: 67,
    size: 13,
  },
  {
    id: "principle-design-engineering",
    kind: "practice",
    label: "ДИЗАЙН-ИНЖЕНЕР",
    title: "ДИЗАЙН-ИНЖЕНЕР",
    meta: "ДИЗАЙН / КОД / РАБОЧИЙ ПРОТОТИП",
    description: "Дизайн-инженер соединяет композицию и код: самостоятельно проектирует решение и доводит его до работающего прототипа. Этот подход мне близок — я одновременно вижу визуальную систему, пользовательский сценарий и технические ограничения.",
    kindLabel: "ПРИНЦИП / 15",
    x: 27,
    y: 66,
    size: 14,
  },
  {
    id: "principle-shaper",
    kind: "practice",
    label: "СКУЛЬПТОР / АРХЕОЛОГ",
    title: "СКУЛЬПТОР / АРХЕОЛОГ",
    meta: "ПРИДАТЬ ФОРМУ / УБРАТЬ ЛИШНЕЕ / НАЙТИ ЦЕННОСТЬ",
    description: "Работаю в двух режимах. Как скульптор — постепенно убираю лишнее, пока не проявится форма. Как археолог — не навязываю решение, а бережно освобождаю уже существующую ценность. В обоих случаях важно вовремя остановиться и не задеть главное.",
    kindLabel: "ПРИНЦИП / 16",
    x: 38,
    y: 64,
    size: 12,
  },
  {
    id: "principle-experiment",
    kind: "practice",
    label: "ГОСТЕПРИИМСТВО + ЗАБОТА",
    title: "ЦИФРОВОЕ ГОСТЕПРИИМСТВО И ЗАБОТА",
    meta: "CX / IXD / ИНКЛЮЗИВНОСТЬ / ГЕНЕРАТИВНЫЙ ИИ",
    description: "Исследую цифровое гостеприимство, инклюзивный веб и генеративный ИИ как инструменты заботы о пользователе. Мне интересны инициативы на стыке ролей — новые процессы и продукты, которых ещё не было. Ищу команды, где такие эксперименты являются законной частью работы.",
    kindLabel: "ПРИНЦИП / 17",
    x: 20,
    y: 77,
    size: 14,
  },
];
