// Runtime module 4/9: deterministic portfolio map data.
const principlesSourceHref = "https://app.notion.com/p/digital-web-digital-f68fc13247614ccb9738d9a85acf29b4?source=copy_link#70405c2623e342fb98d027c8634f2207";

// reel-chapter-manifest:start
const reelChapterSources = new Map([
  ["garage-site", [
      "assets/reel-chapters/garage-site-01.mp4?v=2c74cfcb7562",
      "assets/reel-chapters/garage-site-02.mp4?v=aa6b76a354f6",
  ]],
  ["narkomfin", [
      "assets/reel-chapters/narkomfin-01.mp4?v=8a8b8eba97b7",
      "assets/reel-chapters/narkomfin-02.mp4?v=b0a3640e9a1e",
  ]],
  ["collection", [
      "assets/reel-chapters/garage-collection-01.mp4?v=c458378b08fa",
      "assets/reel-chapters/garage-collection-02.mp4?v=13b73239ecf4",
  ]],
  ["garage-archives", [
      "assets/reel-chapters/garage-archives-01.mp4?v=78c2b0318e41",
      "assets/reel-chapters/garage-archives-02.mp4?v=d86e9d4cf111",
  ]],
  ["garage-courses", [
      "assets/reel-chapters/garage-courses-01.mp4?v=685692edbaeb",
      "assets/reel-chapters/garage-courses-02.mp4?v=295cc2a59b38",
  ]],
  ["garage-webzine", [
      "assets/reel-chapters/garage-webzine-01.mp4?v=78b46830a8ed",
      "assets/reel-chapters/garage-webzine-02.mp4?v=93e6e21719a3",
  ]],
  ["garage-institutions", [
      "assets/reel-chapters/garage-institutions-01.mp4?v=e9516d43f06b",
      "assets/reel-chapters/garage-institutions-02.mp4?v=b138a9b90b19",
  ]],
  ["garage-endowment", [
      "assets/reel-chapters/garage-endowment-01.mp4?v=bd5d5e55e721",
      "assets/reel-chapters/garage-endowment-02.mp4?v=25a4d5b65e08",
  ]],
  ["shirokostup", [
      "assets/reel-chapters/shirokostup-01.mp4?v=9a2ca8be0932",
      "assets/reel-chapters/shirokostup-02.mp4?v=f3312ac0f305",
  ]],
  ["tarski", [
      "assets/reel-chapters/tarski-01.mp4?v=9991bad25583",
      "assets/reel-chapters/tarski-02.mp4?v=ba7327082282",
  ]],
  ["herman", [
      "assets/reel-chapters/herman-01.mp4?v=af3ea87a0934",
      "assets/reel-chapters/herman-02.mp4?v=7196d29d1d8f",
  ]],
  ["hotline-camp", [
      "assets/reel-chapters/hotline-camp-01.mp4?v=de23ead77824",
      "assets/reel-chapters/hotline-camp-02.mp4?v=4f83a0d2671b",
  ]],
  ["dusty", [
      "assets/reel-chapters/dusty-merch-01.mp4?v=7219d4df4177",
      "assets/reel-chapters/dusty-merch-02.mp4?v=fb7fc0b2ed31",
  ]],
  ["dd-camp", [
      "assets/reel-chapters/dusty-camp-01.mp4?v=8a8b672a45a0",
      "assets/reel-chapters/dusty-camp-02.mp4?v=0fec39e9dd30",
  ]],
  ["eleven", [
      "assets/reel-chapters/11111-01.mp4?v=8f3085992002",
      "assets/reel-chapters/11111-02.mp4?v=3ddb427a0153",
  ]],
  ["ks-fish", [
      "assets/reel-chapters/ks-fish-01.mp4?v=d4915d6059f4",
      "assets/reel-chapters/ks-fish-02.mp4?v=08ed32456d91",
  ]],
  ["doronin", [
      "assets/reel-chapters/doronin-01.mp4?v=dbdbce0d7ac3",
      "assets/reel-chapters/doronin-02.mp4?v=cd75b564305b",
  ]],
  ["krainiuk", [
      "assets/reel-chapters/krainiuk-01.mp4?v=6707846bad90",
      "assets/reel-chapters/krainiuk-02.mp4?v=c080a64c42b5",
  ]],
]);
// reel-chapter-manifest:end

const mapItems = [
  {
    id: "garage",
    descriptionCredit: { label: "Charmer Studio", href: "https://www.charmerstudio.com/ru/work/garage" },
    kind: "company",
    label: "Музей «Гараж»",
    title: "Музей «Гараж»",
    meta: "ОКТ 2021—МАР 2025 / СТАРШИЙ МЕНЕДЖЕР ВЕБ-РАЗРАБОТКИ",
    description: "Самый важный профессиональный период: здесь сошлись культура, продукт, исследования, дизайн и масштабная веб-разработка.",
    timeYear: 2023,
    timeLabel: "2021—2025",
    href: "https://garagemca.org/ru",
    kindLabel: "ИНСТИТУЦИЯ / 2021—2025",
    x: 46,
    y: 14,
    size: 76,
  },
  {
    id: "private-practice",
    kind: "project",
    accentKind: "practice",
    label: "Частная практика",
    title: "Частная практика",
    meta: "СЕЙЧАС / НЕБОЛЬШИЕ ЦИФРОВЫЕ ПРОЕКТЫ",
    description: "Самостоятельная работа с небольшими проектами: разобраться в задаче, найти собственную форму и довести продукт до запуска.",
    timeYear: 2023,
    timeLabel: "2020—СЕЙЧАС",
    kindLabel: "ПРАКТИКА / СВЯЗУЮЩИЙ УЗЕЛ",
    x: 61,
    y: 43,
    size: 38,
  },
  {
    id: "optimal",
    kind: "company",
    label: "ОптималГрупп",
    title: "Цифровое агентство «ОптималГрупп»",
    meta: "МАР 2025—АПР 2026 / МЕНЕДЖЕР ПРОЕКТОВ",
    description: "В агентстве вёл клиентские сайты и сервисы; главный кейс — год управления развитием Строительной академии ТЕХНОНИКОЛЬ.",
    caseStudy: {
      title: "Строительная академия ТЕХНОНИКОЛЬ",
      kindLabel: "КЕЙС / ОБРАЗОВАТЕЛЬНЫЙ ПОРТАЛ",
      meta: "ОПТИМАЛГРУПП / МАР 2025—АПР 2026 / МЕНЕДЖЕР ПРОЕКТОВ",
      description: "В цифровом агентстве «ОптималГрупп» год управлял поддержкой и развитием учебного портала Строительной академии ТЕХНОНИКОЛЬ — от приёма проекта до передачи новому менеджеру.",
    },
    timeYear: 2025.5,
    timeLabel: "2025—2026",
    href: "https://optimalgroup.ru/projects/academy-tn-ru/",
    linkLabel: "ОТКРЫТЬ КЕЙС",
    kindLabel: "КОМПАНИЯ / АГЕНТСТВО",
    x: 24,
    y: 18,
    size: 29,
  },
  {
    id: "early-career",
    kind: "company",
    label: "Ранние роли",
    title: "От контента к продукту",
    meta: "ОКТ 2010—АПР 2016 / КОНТЕНТ → ЭЛЕКТРОННАЯ ТОРГОВЛЯ → ПРОДУКТ",
    description: "Начал с контента и электронной торговли в «ВАЛЛЕКС М», затем развивал сайты и интернет-продвижение «ИльмиксГрупп», а в Freya Project уже отвечал за весь продукт — от идеи и UX до продаж, маркетинга и сообщества.",
    timeYear: 2013,
    timeLabel: "2010—2016",
    href: "https://hh.ru/resume/e469b9deff00850af10039ed1f736563726574?print=true",
    linkLabel: "ПОЛНОЕ РЕЗЮМЕ НА HH.RU",
    kindLabel: "ОПЫТ / 2010—2016",
    x: 8,
    y: 22,
    size: 22,
  },
  {
    id: "ilmix",
    kind: "company",
    label: "ИльмиксГрупп",
    title: "«ИльмиксГрупп»",
    caseStudy: { title: "Цифровые продукты «ИльмиксГрупп»" },
    // Final Russian logo: https://readymag.website/hors/next/
    relatedPoster: "assets/project-logos/ilmix.webp",
    previewKind: "logo",
    meta: "ОКОЛО 5 ЛЕТ В СУММЕ / ЦИФРОВОЕ НАПРАВЛЕНИЕ",
    description: "Перезапустил шесть сайтов, занимался разработкой логотипа и остального брендинга. На основе нового бренда курировал разработку всех упаковок продуктов компании. Развивал онкологическое медиа, корпоративные платформы и сервисы для врачей. Отвечал за продуктовую стратегию, UX, рост аудитории, запуск новых каналов и эксперименты с форматами.",
    timeYear: 2018.5,
    timeLabel: "2012—2013 / 2017—2021",
    kindLabel: "КОМПАНИЯ / ВНУТРЕННЯЯ КОМАНДА",
    x: 16,
    y: 30,
    size: 38,
  },
  {
    id: "garage-site",
    descriptionCredit: { label: "Charmer Studio", href: "https://www.charmerstudio.com/ru/work/garage" },
    parent: "garage",
    kind: "project",
    label: "САЙТ МУЗЕЯ",
    title: "САЙТ МУЗЕЯ «ГАРАЖ»",
    meta: "UX / UI / ДИЗАЙН-ИНЖИНИРИНГ / ВЕБ-МЕНЕДЖМЕНТ",
    description: "Развитие сайта Музея «Гараж»: исследования, продуктовые решения, дизайн новых функций и управление разработкой. Стратегия и дизайн сайта — Charmer Studio.",
    timeYear: 2023,
    timeLabel: "2021—2025",
    href: "https://garagemca.org/",
    kindLabel: "ПРОЕКТ / МУЗЕЙ «ГАРАЖ»",
    previewVideo: "assets/reels/garage-site.mp4?v=1e206ffd075d",
    previewPoster: "assets/reel-posters/garage-site.jpg?v=0f474f606e9d",
    previewDuration: 7.8,
    previewOrientation: "landscape",
    previewMeta: "ГЛАВНАЯ И НАВИГАЦИЯ / 00:08",
    x: 58,
    y: 14,
    size: 23,
  },
  {
    id: "narkomfin",
    parent: "garage",
    kind: "project",
    label: "ДОМ НАРКОМФИНА",
    title: "ДОМ НАРКОМФИНА",
    meta: "ДИЗАЙН / UX / UI / ЦИФРОВОЙ ОПЫТ",
    description: "Сайт Дома Наркомфина с интерактивной моделью здания, световыми состояниями и календарём.",
    timeYear: 2023,
    href: "https://narkomfin.ru/",
    kindLabel: "ПРОЕКТ / МУЗЕЙ «ГАРАЖ»",
    previewVideo: "assets/reels/narkomfin.mp4?v=b03bf2a31888",
    previewPoster: "assets/reel-posters/narkomfin.jpg?v=a612d43dea12",
    previewOrientation: "landscape",
    previewMeta: "МОДЕЛЬ, РАЗДЕЛЫ И ТЕМЫ / 00:13",
    x: 67,
    y: 21,
    size: 25,
  },
  {
    id: "collection",
    parent: "garage",
    kind: "project",
    label: "Коллекция",
    title: "Коллекция и открытое хранение",
    meta: "2024 / ПРОДУКТ / ИССЛЕДОВАНИЕ / ЗАПУСК",
    description: "Запуск каталога коллекции и открытого хранения: продуктовая логика, исследования, интерфейс и координация реализации.",
    timeYear: 2024,
    href: "https://garagemca.org/collection/catalogue",
    kindLabel: "ПРОЕКТ / МУЗЕЙ «ГАРАЖ»",
    previewVideo: "assets/reels/garage-collection.mp4?v=83401a311a20",
    previewOrientation: "landscape",
    previewMeta: "КАТАЛОГ И ОТКРЫТОЕ ХРАНЕНИЕ / 00:08",
    x: 75,
    y: 19,
    size: 22,
  },
  {
    id: "garage-archives",
    parent: "garage",
    kind: "project",
    label: "Архивы",
    title: "Архивные проекты",
    meta: "АРХИВ РОССИЙСКОГО ИСКУССТВА / I-M-I / NNS",
    description: "Поддержка и развитие цифровых архивов — от повседневных задач до проектирования новых сценариев доступа к материалам.",
    href: "https://russianartarchive.net/ru",
    kindLabel: "ПРОЕКТ / МУЗЕЙ «ГАРАЖ»",
    previewVideo: "assets/reels/garage-archives.mp4?v=9b3370ed7e66",
    previewPoster: "assets/reel-posters/garage-archives.jpg?v=81aadd292d4e",
    previewOrientation: "landscape",
    previewMeta: "КАТАЛОГ, ПОИСК И АРХИВНЫЕ МАТЕРИАЛЫ / 00:12",
    x: 59,
    y: 28,
    size: 18,
  },
  {
    id: "garage-courses",
    parent: "garage",
    kind: "project",
    label: "Онлайн-курсы",
    title: "Онлайн-курсы Музея",
    meta: "ОБУЧЕНИЕ / ПРОДУКТ / ПАРТНЁРСТВА",
    description: "Бесплатные образовательные продукты: запуск курсов, улучшение сценариев и работа с партнёрами.",
    href: "https://garagemca.org/learn/online-courses",
    kindLabel: "ПРОЕКТ / МУЗЕЙ «ГАРАЖ»",
    previewVideo: "assets/reels/garage-courses.mp4?v=15acbed30144",
    previewOrientation: "landscape",
    previewMeta: "КУРСЫ И УЧЕБНЫЕ СЦЕНАРИИ / 00:07",
    x: 80,
    y: 30,
    size: 17,
  },
  {
    id: "garage-app",
    parent: "garage",
    kind: "project",
    label: "Я иду в музей",
    title: "«Я иду в музей»",
    meta: "ДОСТУПНОСТЬ / МОБИЛЬНЫЙ ПРОДУКТ / ПЕРЕЗАПУСК",
    description: "Перезапуск приложения для людей с ментальными особенностями и их близких: доступность, навигация и понятный маршрут.",
    timeYear: 2024,
    href: "https://apps.apple.com/ru/app/я-иду-в-музей/id1558275984",
    linkLabel: "ОТКРЫТЬ В\u00a0APP STORE",
    kindLabel: "ПРОЕКТ / МУЗЕЙ «ГАРАЖ»",
    x: 84,
    y: 46,
    size: 17,
  },
  {
    id: "garage-webzine",
    parent: "garage",
    kind: "project",
    label: "Веб-зин",
    title: "«Нечеловеческие животные и техника»",
    meta: "ИССЛЕДОВАНИЕ / ДИЗАЙН-ИНЖИНИРИНГ / КОД",
    description: "Интернет-журнал по текстам ридинг-группы, собранный вручную как самостоятельная цифровая форма.",
    href: "https://non-human-animals.garage.digital/index.html",
    kindLabel: "ПРОЕКТ / МУЗЕЙ «ГАРАЖ»",
    previewVideo: "assets/reels/garage-webzine.mp4?v=ffe8ffd234f8",
    previewPoster: "assets/reel-posters/garage-webzine.jpg?v=461addd9b6aa",
    previewOrientation: "landscape",
    previewMeta: "ГЛАВНАЯ, ТЕКСТ И ТЁМНАЯ ТЕМА / 00:12",
    x: 72,
    y: 34,
    size: 15,
  },
  {
    id: "garage-institutions",
    parent: "garage",
    kind: "project",
    label: "Помощь институциям",
    title: "Помощь культурным институциям",
    meta: "КОНСУЛЬТАЦИИ / ДИЗАЙН / ТЕХНИЧЕСКАЯ ПОМОЩЬ",
    description: "Знания, консультации и конкретная техническая помощь культурным институциям и НКО — с акцентом на быстрый запуск.",
    href: "https://radiancecca.com/",
    kindLabel: "ПРОЕКТ / МУЗЕЙ «ГАРАЖ»",
    previewVideo: "assets/reels/garage-institutions.mp4?v=44317e2d8066",
    previewPoster: "assets/reel-posters/garage-institutions.jpg?v=186a13863205",
    previewOrientation: "landscape",
    previewMeta: "СОБЫТИЯ, НАПРАВЛЕНИЯ И ПОСЕЩЕНИЕ / 00:12",
    x: 55,
    y: 37,
    size: 16,
  },
  {
    id: "garage-endowment",
    parent: "garage",
    kind: "project",
    label: "Эндаумент",
    title: "Эндаумент-фонд Музея",
    meta: "ПОДДЕРЖКА / РАЗВИТИЕ / КОНТЕНТ",
    description: "Поддержка и развитие отдельного цифрового продукта эндаумент-фонда Музея.",
    href: "https://endowment.garagemca.org/ru/",
    kindLabel: "ПРОЕКТ / МУЗЕЙ «ГАРАЖ»",
    previewVideo: "assets/reels/garage-endowment.mp4?v=bb8a0d8f6fcd",
    previewPoster: "assets/reel-posters/garage-endowment.jpg?v=60c74c68c8c0",
    previewOrientation: "landscape",
    previewMeta: "МИССИЯ, ЦЕЛЕВЫЕ КАПИТАЛЫ И ПОЖЕРТВОВАНИЕ / 00:11",
    x: 53,
    y: 26,
    size: 12,
  },
  {
    id: "shirokostup",
    parent: "private-practice",
    kind: "project",
    label: "SHIROKOSTUP",
    mapLabel: "Сайт независимого куратора и исследователя Ольги Широкоступ",
    title: "САЙТ ОЛЬГИ ШИРОКОСТУП",
    meta: "РЕДАКЦИОННЫЙ ДИЗАЙН / САЙТ / 2026",
    description: "Кураторская практика и архив проектов Ольги Широкоступ в личном портфолио со спокойным редакционным интерфейсом.",
    timeYear: 2026,
    href: "https://shirokostup.site/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/shirokostup.mp4?v=d7ddd88fb536",
    previewPoster: "assets/reel-posters/shirokostup.jpg?v=74222ef366e9",
    previewOrientation: "landscape",
    previewMeta: "ГЛАВНАЯ, МЕНЮ И ТЁМНАЯ ТЕМА / 00:13",
    x: 78,
    y: 49,
    size: 22,
  },
  {
    id: "tarski",
    parent: "private-practice",
    kind: "project",
    label: "TARSKI",
    mapLabel: "Сайт Tarski — среды для изучения и поддержки социально ориентированного и вовлекающего искусства",
    title: "TARSKI",
    meta: "ЦИФРОВОЙ ПРОДУКТ / САЙТ",
    description: "Первая концептуальная версия сайта молодой культурной институции Tarski. Сайт будет расти и развиваться вместе с ней.",
    timeYear: 2026,
    href: "https://tarski.ru/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/tarski.mp4?v=8c70e36007eb",
    previewOrientation: "landscape",
    previewMeta: "СООБЩЕСТВО И ПРОГРАММА / 00:12",
    x: 70,
    y: 44,
    size: 23,
  },
  {
    id: "herman",
    parent: "private-practice",
    kind: "project",
    label: "HERMAN & CO",
    mapLabel: "Сайт стилиста и эксперта по уходу Германа Винокурова",
    title: "HERMAN & CO",
    meta: "ПРОФИЛЬ / САЙТ",
    description: "Личный сайт Германа Винокурова — человека, который стрижёт, разбирается в моде и стиле, фотографирует, бегает, играет в футбол и любит музыку.",
    timeYear: 2026,
    href: "https://barberherman.ru/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/herman.mp4?v=4f63a85a9558",
    previewPoster: "assets/reel-posters/herman.jpg?v=46c67a36856b",
    previewOrientation: "landscape",
    previewMeta: "ПРОФИЛЬ, МЕДИА И ПЛЕЙЛИСТЫ / 00:15",
    x: 83,
    y: 57,
    size: 19,
  },
  {
    id: "hotline-camp",
    parent: "private-practice",
    relatedTo: ["running"],
    kind: "project",
    label: "HOTLINE CAMP",
    mapLabel: "Сайт предстартового кэмпа по триатлону Hotline Camp",
    title: "HOTLINE CAMP",
    meta: "СОБЫТИЕ / ТРИАТЛОН / САЙТ",
    description: "Сайт предстартового кэмпа в Сочи: программа, тренеры, условия и заявка собраны в ясный маршрут. Визуальная система связывает веб с местом: следует световому дню и откликается на погоду.",
    timeYear: 2026,
    href: "https://hotlinecamp.ru/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/hotline-camp.mp4?v=b0efcbbba5d7",
    previewPoster: "assets/reel-posters/hotline-camp.jpg?v=cc54b4358c35",
    previewOrientation: "landscape",
    previewMeta: "СОЧИНСКАЯ ПАЛИТРА, МЕНЮ И ТРЕНЕРЫ / 00:14",
    x: 63,
    y: 52,
    size: 18,
  },
  {
    id: "dusty",
    parent: "private-practice",
    relatedTo: ["running"],
    kind: "project",
    label: "DUSTY MERCH",
    mapLabel: "Интернет-магазин мерча бегового клуба Dusty\u00a0Dumbbells",
    title: "DUSTY MERCH",
    meta: "МАГАЗИН / САЙТ",
    description: "Небольшой интернет-магазин с собственной визуальной системой и быстрым запуском.",
    timeYear: 2025,
    href: "https://merch.dustydumbbells.com/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/dusty-merch.mp4?v=0a270ae1ed7f",
    previewOrientation: "landscape",
    previewMeta: "КАТАЛОГ И ОФОРМЛЕНИЕ / 00:07",
    x: 69,
    y: 58,
    size: 17,
  },
  {
    id: "dd-camp",
    parent: "private-practice",
    relatedTo: ["running"],
    kind: "project",
    label: "DD CAMP",
    mapLabel: "Сайт осеннего кэмпа Dusty\u00a0Dumbbells",
    title: "DUSTY DUMBBELLS CAMP",
    meta: "СОБЫТИЕ / САЙТ",
    description: "Сайт спортивного кэмпа: программа, атмосфера события и вся практическая информация в одном месте.",
    timeYear: 2025,
    href: "https://camp.dustydumbbells.com/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/dusty-camp.mp4?v=f37879bb3bb6",
    previewOrientation: "landscape",
    previewMeta: "ПРОГРАММА И АТМОСФЕРА / 00:07",
    x: 76,
    y: 57,
    size: 15,
  },
  {
    id: "eleven",
    parent: "private-practice",
    relatedTo: ["running"],
    kind: "project",
    label: "11 111",
    mapLabel: "Сайт проекта «11 111» Виктора Доронина",
    title: "11 111",
    meta: "ИСТОРИЯ / ПАРТНЁРЫ / САЙТ",
    description: "Сайт велопроекта Виктора Доронина: 11 111 км за 31 день в декабре 2026 года. На длинных этапах Виктор будет ехать и днём, и ночью. Чтобы передать этот ритм, я связал палитру и тени на сайте с местным временем Дубая. Утром появляются песочные оттенки, днём поверхности светлеют, на закате свет становится золотистым, ночью — холодным голубым. Облачность приглушает свет и смягчает тени, жара снижает насыщенность фонового видео, ветер задаёт движение лёгкой вуали поверх него, а пыль добавляет песочную дымку. Эти эффекты основаны на данных погодных и атмосферных моделей.",
    timeYear: 2026,
    href: "https://11111.life/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/11111.mp4?v=d5bae9bff1d6",
    previewPoster: "assets/reel-posters/11111.jpg?v=f4fcb946c093",
    previewDuration: 18.7,
    previewOrientation: "landscape",
    previewMeta: "ПАЛИТРА, ПОГОДА И ВРЕМЯ / 00:19",
    x: 64,
    y: 65,
    size: 14,
  },
  {
    id: "ks-fish",
    parent: "private-practice",
    kind: "project",
    label: "РЫБНАЯ ЛАВКА КАПИТАНА СЕЛЁДКИНА",
    mapLabel: "Сайт «Рыбной лавки капитана Селёдкина»",
    title: "РЫБНАЯ ЛАВКА КАПИТАНА СЕЛЁДКИНА",
    meta: "КАТАЛОГ / САЙТ",
    description: "«Рыбная лавка капитана Селёдкина» — мой первый и самый давний частный клиент. На сайте каталог с актуальными ценами соседствует с «Судовым журналом» владельца лавки Олега Гугунавы — рассказами о рыбе, новых привозах и приготовлении. Море на первом экране задаёт настроение, а фотографии и записи Олега знакомят с жизнью лавки ещё до первого визита.",
    timeYear: 2020,
    href: "https://ks.fish/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/ks-fish.mp4?v=43094c44331a",
    previewPoster: "assets/reel-posters/ks-fish.jpg?v=11f18ffdd39c",
    previewDuration: 14.2,
    previewOrientation: "landscape",
    previewMeta: "ГЛАВНАЯ, ЖУРНАЛ И КАТАЛОГ / 00:14",
    x: 58,
    y: 58,
    size: 13,
  },
  {
    id: "doronin",
    parent: "private-practice",
    relatedTo: ["running"],
    kind: "project",
    label: "ДОРОНИН В ДЕЛЕ",
    mapLabel: "Интернет-магазин «Доронин в деле»",
    title: "ДОРОНИН В ДЕЛЕ",
    meta: "МЕРЧ / TILDA / ЭКСПРЕСС-ЗАПУСК",
    description: "Компактная витрина мерча Виктора Доронина — с выразительной подачей и понятным сценарием заказа.",
    timeYear: 2025,
    href: "https://doronin.store/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/doronin.mp4?v=d7fb14430c80",
    previewOrientation: "landscape",
    previewMeta: "КОЛЛЕКЦИЯ И МЕРЧ / 00:07",
    x: 70,
    y: 70,
    size: 13,
  },
  {
    id: "krainiuk",
    parent: "private-practice",
    relatedTo: ["running"],
    kind: "project",
    label: "ЕКАТЕРИНА КРАЙНЮК",
    mapLabel: "Сайт тренера Екатерины Крайнюк",
    title: "ЕКАТЕРИНА КРАЙНЮК",
    meta: "САЙТ ТРЕНЕРА / 2026",
    description: "Плавание, велосипед, бег и триатлон — на сайте можно выбрать своё направление, познакомиться с Катей и её подходом, прочитать отзывы спортсменов. А «Карты на старт» предлагают шуточный прогноз: дисциплину, формат старта и знак на финише.",
    timeYear: 2026,
    href: "https://anton-gorokhovatsky.github.io/ekaterinakrainiuk/",
    kindLabel: "ПРОЕКТ / ЧАСТНАЯ ПРАКТИКА",
    previewVideo: "assets/reels/krainiuk.mp4?v=289bbfd14839",
    previewPoster: "assets/reel-posters/krainiuk.jpg?v=3dfc87246421",
    previewDuration: 29.7,
    previewOrientation: "landscape",
    previewMeta: "ТРЕНИРОВКИ, КАРТЫ И ТЁМНАЯ ТЕМА / 00:30",
    x: 58,
    y: 67,
    size: 18,
  },
  {
    id: "running",
    kind: "personal",
    shape: "sphere",
    label: "БЕГ",
    title: "БЕГ",
    meta: "ЛИЧНЫЙ ЦЕНТР / ДИСТАНЦИЯ / РИТМ",
    description: "Бег — личный центр притяжения: он возвращает ритм, собранность и ощущение движения вперёд — на дистанции и вне её. Через бег я познакомился с людьми, для которых потом сделал Hotline Camp, DD Camp, Dusty Merch, «11 111», doronin.store и сайт Екатерины Крайнюк.",
    href: "https://www.instagram.com/stories/highlights/18054491965888038/",
    linkLabel: "БЕГ В\u00a0INSTAGRAM",
    kindLabel: "ЛИЧНОЕ / ЦЕНТР ПРИТЯЖЕНИЯ",
    x: 50,
    y: 73,
    size: 60,
  },
  {
    id: "art",
    kind: "personal",
    label: "ИСКУССТВО",
    title: "ИСКУССТВО",
    meta: "КУЛЬТУРА / СМОТРЕТЬ ЗАНОВО",
    description: "Не отдельное хобби, а способ смотреть внимательнее и постоянно перенастраивать собственную оптику.",
    href: "https://garagemca.org/calendar",
    linkLabel: "СОБЫТИЯ НА\u00a0САЙТЕ МУЗЕЯ",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 35,
    y: 69,
    size: 17,
  },
  {
    id: "football",
    kind: "personal",
    label: "ФУТБОЛ",
    title: "ФУТБОЛ",
    meta: "СМОТРЕТЬ / ЧИТАТЬ / ОБСУЖДАТЬ",
    description: "Игра, в которой интересны движение, пространство, системы и исключения из них.",
    href: "https://www.sports.ru/tribuna/blogs/vadimlukomski/2249320.html",
    linkLabel: "ЧИТАТЬ СТАТЬЮ",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 48,
    y: 66,
    size: 14,
  },
  {
    id: "snow",
    kind: "personal",
    label: "СНЕГ",
    title: "СНЕГ",
    meta: "СНОУБОРД / ДВИЖЕНИЕ",
    description: "Способ переключить режим внимания и снова почувствовать скорость, склон и тело.",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 43,
    y: 72,
    size: 13,
  },
  {
    id: "music",
    kind: "personal",
    label: "МУЗЫКА",
    title: "МУЗЫКА",
    meta: "СЛУШАТЬ / ПОВТОРЯТЬ",
    description: "Постоянный фон, источник ритма и иногда самый быстрый способ изменить состояние.",
    href: "https://open.spotify.com/track/3GVkPk8mqxz0itaAriG1L7?si=233684c3f400482d",
    linkLabel: "СЛУШАТЬ В\u00a0SPOTIFY",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 27,
    y: 87,
    size: 12,
  },
  {
    id: "coffee",
    kind: "personal",
    label: "КОФЕ",
    title: "КОФЕ",
    meta: "РИТУАЛ / ЧЁРНЫЙ",
    description: "Маленький ежедневный ритуал и уважительный кивок агенту Куперу.",
    href: "https://en.wikipedia.org/wiki/Dale_Cooper",
    linkLabel: "ЧИТАТЬ О\u00a0ДЭЙЛЕ КУПЕРЕ",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 57,
    y: 86,
    size: 10,
  },
  {
    id: "youtube",
    kind: "personal",
    shape: "sphere",
    label: "YOUTUBE",
    title: "YOUTUBE",
    meta: "ИГРЫ / КУПЛИНОВ / «ТЕНЬ ЧЕРНОБЫЛЯ»",
    description: "Люблю YouTube, особенно его игровой сегмент. Самому поиграть получается не\u00a0всегда, но\u00a0смотреть мне тоже нравится. А\u00a0это — великий Дмитрий Куплинов проходит «Тень Чернобыля». Один из\u00a0моих любимых стримов.",
    href: "https://www.youtube.com/watch?v=bkbJsunB5zY",
    linkLabel: "СМОТРЕТЬ НА\u00a0YOUTUBE",
    youtube: {
      videoId: "bkbJsunB5zY",
      title: "Дмитрий Куплинов — «Тень Чернобыля», стрим №\u00a01",
      displayTitle: "«Тень Чернобыля»",
      caption: "Дмитрий Куплинов · Стрим №\u00a01",
      poster: "assets/kuplinov-stalker.jpg",
    },
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 36,
    y: 82,
    size: 42,
  },
  {
    id: "parfyonov",
    kind: "personal",
    shape: "sphere",
    relatedTo: ["youtube"],
    label: "ЛЕОНИД ПАРФЁНОВ",
    title: "ЛЕОНИД ПАРФЁНОВ",
    meta: "ЖУРНАЛИСТИКА / КИНО",
    description: "Леонид Парфёнов — любимый журналист. Восхищаюсь его интересом к жизни, ясностью ума, языком, точностью и умением рассказывать так, что оторваться невозможно",
    quote: {
      text: "«Ну вот были древние греки — а нынешние не от них произошли, и древние египтяне — нынешние не от них, и мы, нынешние русские — не от этих. Сто лет — невелик вроде срок, а случился разрыв цивилизаций, и они для нас — Древняя Россия. Мы не от неё, а от советской»",
      source: "Леонид Парфёнов, «Цвет нации»",
    },
    href: "https://www.youtube.com/playlist?list=PLWC_P718eyWNPChB0IhNYxepf-FoOi-cV",
    linkLabel: "ФИЛЬМЫ ЛЕОНИДА ПАРФЁНОВА",
    kindLabel: "ЛИЧНОЕ / YOUTUBE",
    x: 29,
    y: 73,
    size: 30,
  },
  {
    id: "clayton-young",
    kind: "personal",
    relatedPoster: "assets/personal-previews/clayton-young.jpg",
    relatedTo: ["running", "youtube"],
    label: "КЛЕЙТОН ЯНГ",
    title: "КЛЕЙТОН ЯНГ",
    meta: "БЕГ / ВИДЕОДНЕВНИК",
    description: "Сам бегаю пять раз в неделю и с удовольствием слежу за тем, как бегают и как показывают свой бег мои выдающиеся современники. Уже несколько лет с восторгом смотрю видеодневник Клейтона Янга о подготовке к марафонам — от одного марафонского цикла к следующему.",
    href: "https://www.youtube.com/watch?v=WmO14ECRV48",
    linkLabel: "СМОТРЕТЬ ЭПИЗОД",
    kindLabel: "ЛИЧНОЕ / БЕГ И YOUTUBE",
    x: 46,
    y: 80,
    size: 12,
  },
  {
    id: "beg-vreden",
    kind: "personal",
    relatedPoster: "assets/personal-previews/beg-vreden.jpg",
    relatedPosterShape: "circle",
    relatedTo: ["running", "youtube"],
    label: "БЕГ ВРЕДЕН",
    title: "БЕГ ВРЕДЕН",
    meta: "БЕГ / ПУТЕШЕСТВИЯ / ЛЮДИ",
    description: "Бег, поездки на старты и истории людей вокруг спорта. С удовольствием смотрю, как авторы сами проходят дистанции и показывают этот опыт в своих видео. Благодаря им я снова влюбился в бег.",
    href: "https://www.youtube.com/@BGVRDN",
    linkLabel: "СМОТРЕТЬ КАНАЛ",
    youtube: {
      videoId: "0WI8_H2PTyo",
      href: "https://www.youtube.com/watch?v=0WI8_H2PTyo",
      title: "В чем бегать в 2021 году по красоте",
      displayTitle: "В чем бегать в 2021 году по красоте",
      caption: "Бег Вреден · 2021",
      poster: "assets/personal-previews/beg-vreden-2021.jpg?v=75568cdd20e8",
    },
    kindLabel: "ЛИЧНОЕ / БЕГ И YOUTUBE",
    x: 43,
    y: 87,
    size: 12,
  },
  {
    id: "across-the-runiverse",
    kind: "personal",
    relatedPoster: "assets/personal-previews/across-the-runiverse.jpg",
    relatedTo: ["running", "youtube"],
    label: "ACROSS THE RUNIVERSE",
    title: "ACROSS THE RUNIVERSE",
    meta: "БЕГ / ЛЁГКАЯ АТЛЕТИКА / КОСТЯ КАН",
    description: "Бег изнутри: сборы, тренировки, соревнования. С удовольствием смотрю, как Костя Кан показывает жизнь атлетов. Срыв — легенда!",
    href: "https://www.youtube.com/@Acrosstheruniverse",
    linkLabel: "СМОТРЕТЬ КАНАЛ",
    youtube: {
      videoId: "zNCgPgfxcoM",
      href: "https://www.youtube.com/watch?v=zNCgPgfxcoM",
      title: "Мои атлеты разрывают полумарафон в Дубне. Тестим Saucony Endorphin Pro. ЦЕНЗУРЫ НЕТ",
      displayTitle: "Полумарафон в\u00a0Дубне",
      caption: "Across the Runiverse · Один из\u00a0любимых выпусков",
      poster: "assets/personal-previews/across-dubna.jpg",
    },
    kindLabel: "ЛИЧНОЕ / БЕГ И YOUTUBE",
    x: 53,
    y: 83,
    size: 12,
  },
  {
    id: "wave",
    kind: "personal",
    label: "ВОЛНА",
    title: "ВОЛНА",
    meta: "МОРЕ / ГОРИЗОНТ / МАСШТАБ",
    description: "Открытый горизонт возвращает чувство масштаба и напоминает: за привычными границами всегда есть продолжение.",
    href: "https://www.instagram.com/stories/highlights/17870996476264206/",
    linkLabel: "МОРЕ В\u00a0INSTAGRAM",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 60,
    y: 77,
    size: 12,
  },
  {
    id: "food",
    kind: "personal",
    label: "ЕДА",
    title: "ЕДА",
    meta: "ВКУС / СЕРВИС / ДЕТАЛИ",
    description: "В «Медведе» цель сервиса формулируют без церемоний: сделать так, чтобы гостям буквально снесло крышу. Не от эффектного трюка, а от точности внимания — заметить человека, понять, что для него важно, и выстроить каждую деталь вокруг этого. Для меня здесь сходятся еда, сервис и дизайн. Любить и уважать своё дело — значит прежде всего любить и уважать себя. Отсюда — бесстрашие и желание потратить себя без остатка ради того, что тебе дорого.",
    href: "https://www.fxnetworks.com/shows/the-bear/video-extras/video/64beaaa830c49e0001e758d8",
    linkLabel: "СМОТРЕТЬ ФРАГМЕНТ",
    kindLabel: "ЛИЧНОЕ / ИНТЕРЕС",
    x: 23,
    y: 84,
    size: 10,
  },
  // Principle descriptions are the author's source text. Keep them verbatim;
  // labels, titles and metadata may be edited independently.
  {
    id: "principle-wings",
    kind: "practice",
    label: "ДОВЕРЯТЬ КРЫЛЬЯМ",
    title: "ПТИЦА ДОВЕРЯЕТ КРЫЛЬЯМ",
    meta: "НЕОПРЕДЕЛЁННОСТЬ / ГИБКОСТЬ / РЕЗУЛЬТАТ",
    description: "Несмотря на времена — стандартные вещи перестают работать, сервисы прекращают оказывать услуги, механизмы ломаются, фундаменты рушатся, то, что раньше было очевидно и не обсуждаемо, стало неочевидно и обсуждаемо — в таких условиях задача не в том, чтобы держаться процедур, а в том чтобы перепридумывать их на лету и себя заодно (это же как раз про ту самую гибкость методологии, непрерывное сотрудничество и совершенствование). Я умею двигаться в полной неопределённости и за минимальное количество времени и денег получить результат: ведь суть не в инструментах, а опыте, навыках, знаниях и упорстве, желании делать. Мне нравится поговорка про птицу, что не боится, что ветка под ней сломается — птица доверяет крыльям.",
    kindLabel: "ПРИНЦИП / 01",
    x: 7,
    y: 41,
    size: 14,
  },
  {
    id: "principle-system",
    kind: "practice",
    label: "СИСТЕМНОСТЬ",
    title: "СИСТЕМНЫЙ ПОДХОД",
    meta: "ТЕКУЩЕЕ → ЦЕЛЕВОЕ → РАЗРЫВЫ / ДЕКОМПОЗИЦИЯ",
    description: "Всегда стремлюсь к системному подходу: декомпозирую (AS IS → TO BE → GAP MAP), раскладываю большие задачи на части, оформляю свои решения, мысли, документы в понятном виде и масштабирую лучшие практики. Умею прогнозировать проекты: выстраивать тайминг, успевать к намеченным дедлайнам, оценивать риски.",
    kindLabel: "ПРИНЦИП / 02",
    x: 14,
    y: 37,
    size: 12,
  },
  {
    id: "principle-autonomy",
    kind: "practice",
    label: "САМОСТОЯТЕЛЬНОСТЬ",
    title: "САМОСТОЯТЕЛЬНОСТЬ",
    displayTitle: "САМО\u00adСТОЯ\u00adТЕЛЬ\u00adНОСТЬ",
    meta: "ПРОАКТИВНОСТЬ / УСТОЙЧИВОСТЬ / НАДЁЖНОСТЬ",
    description: "У меня все отлично с самостоятельностью — меня не нужно пушить, контролировать, я проактивно прихожу с вопросами, проблемами и идеями. Проявляю устойчивость к частой смене приоритетов и всегда сохраняю адекватность, трудоспособность, этичность и ответственность — на меня можно реально положиться и просто спокойно работать.",
    kindLabel: "ПРИНЦИП / 03",
    x: 22,
    y: 40,
    size: 11,
  },
  {
    id: "principle-terms",
    kind: "practice",
    label: "ДОКУМЕНТЫ + ФИНАНСЫ",
    title: "ДОКУМЕНТЫ И ФИНАНСЫ",
    meta: "ДОГОВОРЫ / АКТЫ / БЮДЖЕТ",
    description: "Внимателен к документам: сам составляю договоры, не пропускаю детали юридических договоренностей и вовремя закрываю все работы актами. На «ты» обращаюсь с финансами: могу оценить, спланировать бюджет проекта и контролировать его выполнение.",
    kindLabel: "ПРИНЦИП / 04",
    x: 30,
    y: 43,
    size: 10,
  },
  {
    id: "principle-goal",
    kind: "practice",
    label: "ЦЕЛЬ > ФРЕЙМВОРКИ",
    title: "ЦЕЛЬ ВАЖНЕЕ ФРЕЙМВОРКОВ",
    displayTitle: "ЦЕЛЬ ВАЖНЕЕ ФРЕЙМ\u00adВОРКОВ",
    meta: "PMBOK / TRIPLE DIAMOND / JTBD / TDD",
    description: "В работе опираюсь на фреймворки (PMBoK, Triple Diamond от Zendesk, JTBD, test-driven design и все, что оказывается полезным в конкретный момент) и опыт, здравый смысл, идеалы, принципы и ценности. И вообще очень нравится мысль о том, что обсессия средствами производства — частый синдром отсутствия смысла своей деятельности. Когда ты четко понимаешь цель, тебе вообще не нужны фреймворки, системы приоритизации и таск-менеджеры.",
    kindLabel: "ПРИНЦИП / 05",
    x: 10,
    y: 45,
    size: 13,
  },
  {
    id: "principle-improve",
    kind: "practice",
    label: "УПРАВЛЯТЬ + УЛУЧШАТЬ",
    title: "УПРАВЛЯТЬ И УЛУЧШАТЬ",
    meta: "ПРОЕКТЫ / КОМАНДА / ПРОЦЕССЫ",
    description: "За последние несколько лет успешно управлял, координировал и руководил проектами (и командой до 10 человек) с различной степенью сложности, включая масштабные и многоэтапные, соблюдая бюджет и сроки. Постоянно внедряю новые инструменты, технологии и методологии управления проектами, обучаю команду, проактивно инициирую и поддерживаю инициативы других по улучшению процессов и повышению эффективности, что приводит к улучшению качества, оптимизации, уменьшению сроков выполнения рутинных задач и снижению стоимости их реализации. К примеру, больше дизайна сейчас делаем сами в Figma, собирая макеты и лишь на финальном этапе обращаясь к внешним арт-директорам; сменил Mailchimp на Юнисендер для всей команды: сначала освоил сам, унифицировал все шаблоны писем, а затем обучил коллег работе в новом инструменте — по итогу письма собираем быстрее и растим OR, а затраты на сервис снизил в 4 раза.",
    kindLabel: "ПРИНЦИП / 06",
    x: 18,
    y: 43,
    size: 12,
  },
  {
    id: "principle-communicate",
    kind: "practice",
    label: "ЛИДЕР + КОММУНИКАТОР",
    title: "ЛИДЕР И КОММУНИКАТОР",
    displayTitle: "ЛИДЕР И КОМ\u00adМУ\u00adНИ\u00adКА\u00adТОР",
    meta: "ДОГОВАРИВАТЬСЯ / МОТИВИРОВАТЬ / АРГУМЕНТИРОВАТЬ",
    description: "Я лидер и уверенный коммуникатор — легко могу договариваться с внешними людьми и замотивировать свою команду. Коммуникабелен: могу уверенно рассказать о результате работ, работать с возражениями и аргументировать свою позицию независимо от того, с кем общаюсь.",
    kindLabel: "ПРИНЦИП / 07",
    x: 26,
    y: 55,
    size: 12,
  },
  {
    id: "principle-own",
    kind: "practice",
    label: "БРАТЬ ОТВЕТСТВЕННОСТЬ",
    title: "РЕШЕНИЕ И ОТВЕТСТВЕННОСТЬ",
    displayTitle: "РЕ\u00adШЕ\u00adНИЕ И ОТ\u00adВЕТ\u00adСТВЕН\u00adНОСТЬ",
    meta: "РЕШЕНИЕ / ОТВЕТСТВЕННОСТЬ / ХЛАДНОКРОВИЕ",
    description: "Не боюсь принимать решения и брать на себя ответственность за них. Понимаю, что нет нерешаемых задач и в любой ситуации остаюсь хладнокровным.",
    kindLabel: "ПРИНЦИП / 08",
    x: 35,
    y: 54,
    size: 11,
  },
  {
    id: "principle-learn",
    kind: "practice",
    label: "УЧИТЬСЯ + ЗАМЕЧАТЬ",
    title: "УЧИТЬСЯ И ВЕРИТЬ В ДЕТАЛИ",
    meta: "УЧИТЬСЯ / НАБЛЮДАТЬ / НАХОДИТЬ",
    description: "Люблю учиться и с энтузиазмом развиваю новые умения и навыки. Оперативно нахожу нужную информацию, внимательно наблюдаю и верю в силу деталей.",
    kindLabel: "ПРИНЦИП / 09",
    x: 7,
    y: 58,
    size: 10,
  },
  {
    id: "principle-ideas",
    kind: "practice",
    label: "ИДЕИ + ТРЕНДЫ",
    title: "КРЕАТИВНЫЕ ИДЕИ И ТРЕНДЫ",
    meta: "ЦИФРОВАЯ СРЕДА / МЕДИА / ТЕХНОЛОГИИ",
    description: "Обладаю способностью быстро генерировать креативные идеи и решения. Слежу за цифровыми- и медиа-трендами, развивающимися технологиями и платформами.",
    kindLabel: "ПРИНЦИП / 10",
    x: 15,
    y: 57,
    size: 11,
  },
  {
    id: "principle-language",
    kind: "practice",
    label: "РУССКИЙ ЯЗЫК",
    title: "ГРАМОТНЫЙ РУССКИЙ ЯЗЫК",
    meta: "ЦИФРОВОЙ ЭТИКЕТ / ПУНКТУАЦИЯ / ГРАММАТИКА",
    description: "Неустанно оттачиваю грамотный русский язык: цифровой этикет, пунктуацию и грамматику.",
    kindLabel: "ПРИНЦИП / 11",
    x: 22,
    y: 60,
    size: 9,
  },
  {
    id: "principle-tools",
    kind: "practice",
    label: "БЫСТРО НАЙТИ ПОДХОД",
    title: "БЫСТРО НАЙТИ ПОДХОД",
    meta: "FIGMA / NOTION / КОД / ИИ / И ДАЛЬШЕ",
    description: "На «ты» с Figma, Photoshop, Notion, Trello, Jira, MailChimp, UniSender, Tilda, Readymag, Webflow, Miro, FigJam, JSON, HTML, большими языковыми моделями и нейросетями — а с чем ещё нет, то гарантированно быстро найду к этому подход.",
    kindLabel: "ПРИНЦИП / 12",
    x: 31,
    y: 58,
    size: 10,
  },
  {
    id: "principle-now",
    kind: "practice",
    label: "НОВОЕ — СЕЙЧАС",
    title: "НОВОЕ — ПРЯМО СЕЙЧАС",
    meta: "ИННОВАЦИИ / OPENAI / ПОВСЕДНЕВНАЯ РАБОТА",
    description: "Инновации: беру всё новое и лучшее и применяю прямо сейчас в повседневных задачах — вижу именно в этом смысл своей работы. Например, с продуктами OpenAI применяю два принципа: принцип первый — нельзя не использовать ChatGPT; принцип второй — участие ChatGPT не должно быть заметно.",
    kindLabel: "ПРИНЦИП / 13",
    x: 10,
    y: 68,
    size: 11,
  },
  {
    id: "principle-data-intuition",
    kind: "practice",
    label: "ЦИФРЫ + ИНТУИЦИЯ",
    title: "АНАЛИТИКА И ИНТУИЦИЯ",
    meta: "ДАННЫЕ / ВПЕЧАТЛЕНИЯ / ДОСТУПНОСТЬ",
    description: "C одной стороны считаю, что лучшие менеджеры — это аналитики, которые лучше всех на цифрах понимают как работает продукт, и имеют огромное желание свои исследования превратить в реальные продуктовые изменения и стараюсь это качество в себе развить. С другой стороны не понимаю, как можно придумать классный продукт на A/B-тестах и фокус-группах. На них можно сделать классный продукт на 2 % лучше, а плохой продукт не улучшат никакие тесты. Поэтому занимаясь созданием чего-то, придумыванием, думаю не цифрами, а интуицией (Эндрю Чен вот здесь пишет о том, что управлять на основе данных — сложная и часто невозможная задача) — думаю о дизайне впечатлений и снижении стоимости взаимодействия, доступности (быть дружелюбными и демократизировать технологии для людей, фокусироваться на человеческих потребностях и мотивах), идеалах, принципах и ценностях. Цифры не предскажут трепета и возбуждения, которые возникают в душе от хорошей идеи.",
    kindLabel: "ПРИНЦИП / 14",
    x: 18,
    y: 67,
    size: 13,
  },
  {
    id: "principle-design-engineering",
    kind: "practice",
    label: "ДИЗАЙН-ИНЖЕНЕР",
    title: "ДИЗАЙН-ИНЖЕНЕР",
    meta: "ДИЗАЙН / КОД / РАБОЧИЙ ПРОТОТИП",
    description: "Мехмет Байтас написал о дизайн-инженерах — универсальных специалистах, которые сочетают в себе навыки и дизайнера, и разработчика. Они могут самостоятельно спроектировать дизайн и довести его до рабочего прототипа, написав код. Вот всегда думаю и о себе в таком ключе: одновременно чувствую и композицию, и технические ограничения.",
    kindLabel: "ПРИНЦИП / 15",
    x: 27,
    y: 66,
    size: 14,
  },
  {
    id: "principle-shaper",
    kind: "practice",
    label: "СКУЛЬПТОР / АРХЕОЛОГ",
    title: "СКУЛЬПТОР / АРХЕОЛОГ",
    meta: "ПРИДАТЬ ФОРМУ / УБРАТЬ ЛИШНЕЕ / НАЙТИ ЦЕННОСТЬ",
    description: "Я встречал ещё пару метафор своего подхода к работе. Иногда такая роль называется «shaper» (придающий форму): подобно скульптору, вы постепенно откалываете лишнее, чтобы оставить суть. Ещё один вариант — сравнение с работой археолога; в отличие от скульптора, вы не принимаете творческих решений: нужная людям ценность уже хранится под толщей земли, и нужно методично убирать лишнее, не задевая важного.",
    kindLabel: "ПРИНЦИП / 16",
    x: 38,
    y: 64,
    size: 12,
  },
  {
    id: "principle-experiment",
    kind: "practice",
    label: "ГОСТЕПРИИМСТВО + ЗАБОТА",
    title: "ЦИФРОВОЕ ГОСТЕПРИИМСТВО И ЗАБОТА",
    displayTitle: "ЦИФ\u00adРО\u00adВОЕ ГОС\u00adТЕ\u00adПРИ\u00adИМ\u00adСТВО И ЗА\u00adБО\u00adТА",
    meta: "CX / IXD / ИНКЛЮЗИВНОСТЬ / ГЕНЕРАТИВНЫЙ ИИ",
    description: "Области интереса сейчас: CX и IxD — «цифровое» гостеприимство и забота, как я понимаю их, инклюзивные практики в веб-дизайне и веб-продакшне. Генеративный искусственный интеллект в контексте этих точек интереса. Мне всегда было интересно то, чем занимаются люди на позициях «продакт-проджект-гроус-хакеров» или «ченджеров» — создавать внутри компании то, чего ещё не было: Такие проекты не всегда про IT, не по должностной инструкции, не будут оплачены отдельно, но мне интересно это сделать, потому что это кажется возможным и важным, новым. Если говорить тут о «работодателе / проекте мечты», то хотелось бы быть частью компании, которая осознаёт важность экспериментов и даёт экспериментировать «легально».",
    kindLabel: "ПРИНЦИП / 17",
    x: 20,
    y: 77,
    size: 14,
  },
];

// One project name is reused by the map, search, lists and the reading frame.
const projectNames = {
  "garage-site": "Сайт Музея «Гараж»",
  "narkomfin": "Дом Наркомфина",
  "shirokostup": "Ольга Широкоступ",
  "tarski": "Tarski",
  "herman": "Герман Винокуров",
  "hotline-camp": "Hotline Camp",
  "dusty": "Dusty Merch",
  "dd-camp": "DD Camp",
  "eleven": "11\u00a0111 — Виктор Доронин",
  "ks-fish": "Рыбная лавка капитана Селёдкина",
  "doronin": "Доронин в\u00a0деле",
  "krainiuk": "Екатерина Крайнюк",
};
for (const item of mapItems) {
  if (projectNames[item.id]) item.label = item.title = projectNames[item.id];
}

// Unaltered frames from the existing 900×600 masters; time records the source.
// ks.fish and the Narkomfin night view use public browser captures from
// 2026-10-03 (null time), retaining their original aspect ratios.
const caseFigures = {
  "narkomfin": [
    ["task", "assets/case-figures/narkomfin-1.jpg", 3, "Дневная модель Дома Наркомфина", "Модель здания помогает знакомиться с\u00a0местами внутри дома через саму архитектуру."],
    ["result", "assets/case-figures/narkomfin-2.jpg?v=3a13718cebb1", null, "Ночная модель Дома Наркомфина", "Дневное и\u00a0ночное освещение меняют восприятие одной и\u00a0той\u00a0же модели."],
  ],
  "shirokostup": [
    ["task", "assets/case-figures/shirokostup-1.jpg", 3.5, "Оглавление портфолио Ольги Широкоступ", "Общее оглавление делает разные направления кураторской практики доступными из\u00a0одного места."],
    ["result", "assets/case-figures/shirokostup-2.jpg", 10, "Раздел проектов Ольги Широкоступ", "Избранные работы и\u00a0долгосрочные проекты получают собственный редакционный ритм."],
  ],
  "tarski": [
    ["task", "assets/case-figures/tarski-1.jpg", 2.5, "Редакционный раздел Tarski", "Текст, программа и\u00a0изображения знакомят с\u00a0направлением работы институции."],
    ["result", "assets/case-figures/tarski-2.jpg", 10, "Сообщество и досье Tarski", "Сеть участников связывает общую программу с\u00a0конкретными людьми и\u00a0их практиками."],
  ],
  "eleven": [
    ["task", "assets/case-figures/11111-1.jpg", 6, "Навигация и погодные данные проекта 11 111", "Погода и\u00a0освещение связывают страницу с\u00a0местом и\u00a0временем заезда."],
    ["result", "assets/case-figures/11111-2.jpg", 14, "Свет и тень на сайте 11 111", "Свет и\u00a0тень связывают визуальную среду сайта со\u00a0временем суток."],
  ],
  "herman": [
    ["task", "assets/case-figures/herman-1.jpg", 3, "Профиль Германа Винокурова", "Практика и\u00a0экспертиза соседствуют с\u00a0личными увлечениями, сохраняя цельный портрет человека."],
    ["result", "assets/case-figures/herman-2.jpg", 13.8, "Музыка и медиа Германа Винокурова", "Музыка получает своё место в\u00a0личном сайте — с\u00a0обложкой и\u00a0трек-листом."],
  ],
  "ks-fish": [
    ["idea", "assets/case-figures/ks-fish-1.jpg", null, "Запись Судового журнала с фотографией, текстом и переходом к заказу", "У\u00a0каждой записи — полный авторский текст, фотография, дата и\u00a0возможность спросить о\u00a0наличии рыбы."],
    ["result", "assets/case-figures/ks-fish-2.jpg", null, "Поиск по слову «креветки»: пять товаров с ценами и ссылками заказа", "Поиск понимает привычные названия: «креветки» находит позиции «Креветка». Цена и\u00a0переход к\u00a0заказу остаются рядом."],
  ],
};
for (const item of mapItems) {
  item.figures = (caseFigures[item.id] || []).map(([field, file, time, alt, caption, size = [900, 600]]) => ({
    field, src: file, time, alt, caption, width: size[0], height: size[1],
  }));
}
const getMapPreviewPoster = item => item.relatedPoster || item.previewPoster || item.youtube?.poster
  || item.previewVideo?.split("?")[0].replace("assets/reels/", "assets/reel-posters/").replace(/\.mp4$/i, ".jpg") || "";

export {
  getMapPreviewPoster,
  mapItems,
  principlesSourceHref,
  reelChapterSources,
};
